// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type AdditionalRestriction struct {

	// Policy: Detailed information about the policy document that defines this restriction, including policy metadata, type, scope, and the specific rules or conditions that implement the access control.
	Policy Policy `json:"policy" parquet:"policy"`

	// Status: The current status of the policy restriction, normalized to the caption of the <code>status_id</code> enum value.
	Status *string `json:"status,omitempty" parquet:"status,optional"`

	// Status ID: The normalized status identifier indicating the applicability of this policy restriction.
	StatusId *int32 `json:"status_id,omitempty" parquet:"status_id,optional"`
}

func (v *AdditionalRestriction) Observable() (*int, string) {
	return nil, ""
}

var AdditionalRestrictionFields = []arrow.Field{
	{Name: "policy", Type: PolicyStruct, Nullable: false},
	{Name: "status", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "status_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
}

var AdditionalRestrictionStruct = arrow.StructOf(AdditionalRestrictionFields...)

var AdditionalRestrictionSchema = arrow.NewSchema(AdditionalRestrictionFields, nil)
var AdditionalRestrictionClassname = "additional_restriction"
