// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type AffectedCode struct {

	// End Column: The column number of the last part of the assessed code identified as vulnerable.
	EndColumn *int32 `json:"end_column,omitempty" parquet:"end_column,optional"`

	// End Line: The line number of the last line of code block identified as vulnerable.
	EndLine *int32 `json:"end_line,omitempty" parquet:"end_line,optional"`

	// File: Details about the file that contains the affected code block.
	File File `json:"file" parquet:"file"`

	// Owner: Details about the user that owns the affected file.
	Owner *User `json:"owner,omitempty" parquet:"owner,optional"`

	// Remediation Guidance: Describes the recommended remediation steps to address identified issue(s).
	Remediation *Remediation `json:"remediation,omitempty" parquet:"remediation,optional"`

	// Related Rule: Details about the specific rule, e.g., those defined as part of a larger <code>policy</code>, that triggered the finding.
	Rule *Rule `json:"rule,omitempty" parquet:"rule,optional"`

	// Start Column: The column number of the first part of the assessed code identified as vulnerable.
	StartColumn *int32 `json:"start_column,omitempty" parquet:"start_column,optional"`

	// Start Line: The line number of the first line of code block identified as vulnerable.
	StartLine *int32 `json:"start_line,omitempty" parquet:"start_line,optional"`
}

func (v *AffectedCode) Observable() (*int, string) {
	return nil, ""
}

var AffectedCodeFields = []arrow.Field{
	{Name: "end_column", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "end_line", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "file", Type: FileStruct, Nullable: false},
	{Name: "owner", Type: UserStruct, Nullable: true},
	{Name: "remediation", Type: RemediationStruct, Nullable: true},
	{Name: "rule", Type: RuleStruct, Nullable: true},
	{Name: "start_column", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "start_line", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
}

var AffectedCodeStruct = arrow.StructOf(AffectedCodeFields...)

var AffectedCodeSchema = arrow.NewSchema(AffectedCodeFields, nil)
var AffectedCodeClassname = "affected_code"
