// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type AnalysisTarget struct {

	// Name: The specific name or identifier of the analysis target, such as the username of a User Account, the name of a Kubernetes Cluster, the identifier of a Network Namespace, or the name of an Application Component.
	Name string `json:"name" parquet:"name"`

	// Type: The category of the analysis target, such as User Account, Kubernetes Cluster, Network Namespace, or Application Component.
	Type *string `json:"type,omitempty" parquet:"type,optional"`
}

func (v *AnalysisTarget) Observable() (*int, string) {
	return nil, ""
}

var AnalysisTargetFields = []arrow.Field{
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: false},
	{Name: "type", Type: arrow.BinaryTypes.String, Nullable: true},
}

var AnalysisTargetStruct = arrow.StructOf(AnalysisTargetFields...)

var AnalysisTargetSchema = arrow.NewSchema(AnalysisTargetFields, nil)
var AnalysisTargetClassname = "analysis_target"
