// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type API struct {

	// Group: The information pertaining to the API group.
	Group *Group `json:"group,omitempty" parquet:"group,optional"`

	// Operation: Verb/Operation associated with the request
	Operation string `json:"operation" parquet:"operation"`

	// API Request Details: Details pertaining to the API request.
	Request *RequestElements `json:"request,omitempty" parquet:"request,optional"`

	// API Response Details: Details pertaining to the API response.
	Response *ResponseElements `json:"response,omitempty" parquet:"response,optional"`

	// Service: The information pertaining to the API service.
	Service *Service `json:"service,omitempty" parquet:"service,optional"`

	// Version: The version of the API service.
	Version *string `json:"version,omitempty" parquet:"version,optional"`
}

func (v *API) Observable() (*int, string) {
	return nil, ""
}

var APIFields = []arrow.Field{
	{Name: "group", Type: GroupStruct, Nullable: true},
	{Name: "operation", Type: arrow.BinaryTypes.String, Nullable: false},
	{Name: "request", Type: RequestElementsStruct, Nullable: true},
	{Name: "response", Type: ResponseElementsStruct, Nullable: true},
	{Name: "service", Type: ServiceStruct, Nullable: true},
	{Name: "version", Type: arrow.BinaryTypes.String, Nullable: true},
}

var APIStruct = arrow.StructOf(APIFields...)

var APISchema = arrow.NewSchema(APIFields, nil)
var APIClassname = "api"
