// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type MITREATTCKATLAS struct {

	// MITRE Mitigation: The Mitigation object describes the MITRE ATT&CK® or ATLAS™ Mitigation ID and/or name that is associated to an attack.
	Mitigation *MITREMitigation `json:"mitigation,omitempty" parquet:"mitigation,optional"`

	// MITRE Sub-technique: The Sub-technique object describes the MITRE ATT&CK® or ATLAS™ Sub-technique ID and/or name associated to an attack.
	SubTechnique *MITRESubtechnique `json:"sub_technique,omitempty" parquet:"sub_technique,optional"`

	// MITRE Tactic: The Tactic object describes the MITRE ATT&CK® or ATLAS™ Tactic ID and/or name that is associated to an attack.
	Tactic *MITRETactic `json:"tactic,omitempty" parquet:"tactic,optional"`

	// MITRE Technique: The Technique object describes the MITRE ATT&CK® or ATLAS™ Technique ID and/or name associated to an attack.
	Technique *MITRETechnique `json:"technique,omitempty" parquet:"technique,optional"`

	// Version: The ATT&CK® or ATLAS™ Matrix version.
	Version *string `json:"version,omitempty" parquet:"version,optional"`
}

func (v *MITREATTCKATLAS) Observable() (*int, string) {
	return nil, ""
}

var MITREATTCKATLASFields = []arrow.Field{
	{Name: "mitigation", Type: MITREMitigationStruct, Nullable: true},
	{Name: "sub_technique", Type: MITRESubtechniqueStruct, Nullable: true},
	{Name: "tactic", Type: MITRETacticStruct, Nullable: true},
	{Name: "technique", Type: MITRETechniqueStruct, Nullable: true},
	{Name: "version", Type: arrow.BinaryTypes.String, Nullable: true},
}

var MITREATTCKATLASStruct = arrow.StructOf(MITREATTCKATLASFields...)

var MITREATTCKATLASSchema = arrow.NewSchema(MITREATTCKATLASFields, nil)
var MITREATTCKATLASClassname = "attack"
