// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type AuthenticationFactor struct {

	// Device: Device used to complete an authentication request.
	Device *Device `json:"device,omitempty" parquet:"device,optional"`

	// Email Address: The email address used in an email-based authentication factor.
	EmailAddr *string `json:"email_addr,omitempty" parquet:"email_addr,optional"`

	// Factor Type: The type of authentication factor used in an authentication attempt.
	FactorType *string `json:"factor_type,omitempty" parquet:"factor_type,optional"`

	// Factor Type ID: The normalized identifier for the authentication factor.
	FactorTypeId int32 `json:"factor_type_id" parquet:"factor_type_id"`

	// HMAC-based One-time Password (HOTP): Whether the authentication factor is an HMAC-based One-time Password (HOTP).
	IsHotp *bool `json:"is_hotp,omitempty" parquet:"is_hotp,optional"`

	// Time-based One-time Password (TOTP): Whether the authentication factor is a Time-based One-time Password (TOTP).
	IsTotp *bool `json:"is_totp,omitempty" parquet:"is_totp,optional"`

	// Phone Number: The phone number used for a telephony-based authentication request.
	PhoneNumber *string `json:"phone_number,omitempty" parquet:"phone_number,optional"`

	// Provider: The name of provider for an authentication factor.
	Provider *string `json:"provider,omitempty" parquet:"provider,optional"`

	// Security Questions: The question(s) provided to user for a question-based authentication factor.
	SecurityQuestions []string `json:"security_questions,omitempty" parquet:"security_questions,list,optional"`
}

func (v *AuthenticationFactor) Observable() (*int, string) {
	return nil, ""
}

var AuthenticationFactorFields = []arrow.Field{
	{Name: "device", Type: DeviceStruct, Nullable: true},
	{Name: "email_addr", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "factor_type", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "factor_type_id", Type: arrow.PrimitiveTypes.Int32, Nullable: false},
	{Name: "is_hotp", Type: arrow.FixedWidthTypes.Boolean, Nullable: true},
	{Name: "is_totp", Type: arrow.FixedWidthTypes.Boolean, Nullable: true},
	{Name: "phone_number", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "provider", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "security_questions", Type: arrow.ListOf(arrow.BinaryTypes.String), Nullable: true},
}

var AuthenticationFactorStruct = arrow.StructOf(AuthenticationFactorFields...)

var AuthenticationFactorSchema = arrow.NewSchema(AuthenticationFactorFields, nil)
var AuthenticationFactorClassname = "auth_factor"
