// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type AutonomousSystem struct {

	// Name: Organization name for the Autonomous System.
	Name *string `json:"name,omitempty" parquet:"name,optional"`

	// Number: Unique number that the AS is identified by.
	Number *int32 `json:"number,omitempty" parquet:"number,optional"`
}

func (v *AutonomousSystem) Observable() (*int, string) {
	return nil, ""
}

var AutonomousSystemFields = []arrow.Field{
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "number", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
}

var AutonomousSystemStruct = arrow.StructOf(AutonomousSystemFields...)

var AutonomousSystemSchema = arrow.NewSchema(AutonomousSystemFields, nil)
var AutonomousSystemClassname = "autonomous_system"
