// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type Campaign struct {

	// Name: The name of a specific campaign associated with a cyber threat.
	Name string `json:"name" parquet:"name"`
}

func (v *Campaign) Observable() (*int, string) {
	return nil, ""
}

var CampaignFields = []arrow.Field{
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: false},
}

var CampaignStruct = arrow.StructOf(CampaignFields...)

var CampaignSchema = arrow.NewSchema(CampaignFields, nil)
var CampaignClassname = "campaign"
