// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type CISControl struct {

	// Description: The CIS Control description. For example: <i>Uninstall or disable unnecessary services on enterprise assets and software, such as an unused file sharing service, web application module, or service function.</i>
	Desc *string `json:"desc,omitempty" parquet:"desc,optional"`

	// Name: The CIS Control name. For example: <i>4.8 Uninstall or Disable Unnecessary Services on Enterprise Assets and Software.</i>
	Name string `json:"name" parquet:"name"`

	// Version: The CIS Control version. For example: <i>v8</i>.
	Version *string `json:"version,omitempty" parquet:"version,optional"`
}

func (v *CISControl) Observable() (*int, string) {
	return nil, ""
}

var CISControlFields = []arrow.Field{
	{Name: "desc", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: false},
	{Name: "version", Type: arrow.BinaryTypes.String, Nullable: true},
}

var CISControlStruct = arrow.StructOf(CISControlFields...)

var CISControlSchema = arrow.NewSchema(CISControlFields, nil)
var CISControlClassname = "cis_control"
