// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type CISCSC struct {

	// Security Control: A Control is prescriptive, prioritized, and simplified set of best practices that one can use to strengthen their cybersecurity posture. e.g. AWS SecurityHub Controls, CIS Controls.
	Control string `json:"control" parquet:"control"`

	// Version: The CIS critical security control version.
	Version *string `json:"version,omitempty" parquet:"version,optional"`
}

func (v *CISCSC) Observable() (*int, string) {
	return nil, ""
}

var CISCSCFields = []arrow.Field{
	{Name: "control", Type: arrow.BinaryTypes.String, Nullable: false},
	{Name: "version", Type: arrow.BinaryTypes.String, Nullable: true},
}

var CISCSCStruct = arrow.StructOf(CISCSCFields...)

var CISCSCSchema = arrow.NewSchema(CISCSCFields, nil)
var CISCSCClassname = "cis_csc"
