// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type ClassifierDetails struct {

	// Name: The name of the classifier.
	Name *string `json:"name,omitempty" parquet:"name,optional"`

	// Type: The type of the classifier.
	Type string `json:"type" parquet:"type"`

	// Unique ID: The unique identifier of the classifier.
	Uid *string `json:"uid,omitempty" parquet:"uid,optional"`
}

func (v *ClassifierDetails) Observable() (*int, string) {
	return nil, ""
}

var ClassifierDetailsFields = []arrow.Field{
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "type", Type: arrow.BinaryTypes.String, Nullable: false},
	{Name: "uid", Type: arrow.BinaryTypes.String, Nullable: true},
}

var ClassifierDetailsStruct = arrow.StructOf(ClassifierDetailsFields...)

var ClassifierDetailsSchema = arrow.NewSchema(ClassifierDetailsFields, nil)
var ClassifierDetailsClassname = "classifier_details"
