// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"fmt"

	"github.com/apache/arrow-go/v18/arrow"
	"github.com/telophasehq/go-ocsf/ocsf"
)

type DataSecurityFinding struct {

	// Action: The normalized caption of <code>action_id</code>.
	Action *string `json:"action,omitempty" parquet:"action,optional"`

	// Action ID: The action taken by a control or other policy-based system leading to an outcome or disposition. An unknown action may still correspond to a known disposition. Refer to <code>disposition_id</code> for the outcome of the action.
	ActionId *int32 `json:"action_id,omitempty" parquet:"action_id,optional"`

	// Activity ID: The normalized identifier of the Data Security Finding activity.
	ActivityId int32 `json:"activity_id" parquet:"activity_id"`

	// Activity: The Data Security finding activity name, as defined by the <code>activity_id</code>.
	ActivityName *string `json:"activity_name,omitempty" parquet:"activity_name,optional"`

	// Actor: Describes details about the actor implicated in the data security finding. Either an actor that owns a particular digital file or information store, or an actor which accessed classified or sensitive data.
	Actor *Actor `json:"actor,omitempty" parquet:"actor,optional"`

	// API Details: Describes details about a typical API (Application Programming Interface) call.
	Api *API `json:"api,omitempty" parquet:"api,optional"`

	// Assignee: The details of the user assigned to an Incident.
	Assignee *User `json:"assignee,omitempty" parquet:"assignee,optional"`

	// Assignee Group: The details of the group assigned to an Incident.
	AssigneeGroup *Group `json:"assignee_group,omitempty" parquet:"assignee_group,optional"`

	// MITRE ATT&CK® and ATLAS™ Details: An array of MITRE ATT&CK® objects describing identified tactics, techniques & sub-techniques. The objects are compatible with MITRE ATLAS™ tactics, techniques & sub-techniques.
	Attacks []MITREATTCKATLAS `json:"attacks,omitempty" parquet:"attacks,list,optional"`

	// Authorization Information: Provides details about an authorization, such as authorization outcome, and any associated policies related to the activity/event.
	Authorizations []AuthorizationResult `json:"authorizations,omitempty" parquet:"authorizations,list,optional"`

	// Category: The event category name, as defined by category_uid value: <code>Findings</code>.
	CategoryName *string `json:"category_name,omitempty" parquet:"category_name,optional"`

	// Category ID: The category unique identifier of the event.
	CategoryUid int32 `json:"category_uid" parquet:"category_uid"`

	// Class: The event class name, as defined by class_uid value: <code>Data Security Finding</code>.
	ClassName *string `json:"class_name,omitempty" parquet:"class_name,optional"`

	// Class ID: The unique identifier of a class. A class describes the attributes available in an event.
	ClassUid int32 `json:"class_uid" parquet:"class_uid"`

	// Comment: A user provided comment about the finding.
	Comment *string `json:"comment,omitempty" parquet:"comment,optional"`

	// Confidence: The confidence, normalized to the caption of the confidence_id value. In the case of 'Other', it is defined by the event source.
	Confidence *string `json:"confidence,omitempty" parquet:"confidence,optional"`

	// Confidence ID: The normalized confidence refers to the accuracy of the rule that created the finding. A rule with a low confidence means that the finding scope is wide and may create finding reports that may not be malicious in nature.
	ConfidenceId *int32 `json:"confidence_id,omitempty" parquet:"confidence_id,optional"`

	// Confidence Score: The confidence score as reported by the event source.
	ConfidenceScore *int32 `json:"confidence_score,omitempty" parquet:"confidence_score,optional"`

	// Count: The number of times that events in the same logical group occurred during the event <strong>Start Time</strong> to <strong>End Time</strong> period.
	Count *int32 `json:"count,omitempty" parquet:"count,optional"`

	// Data Security: The Data Security object describes the characteristics, techniques and content of a Data Loss Prevention (DLP), Data Loss Detection (DLD), Data Classification, or similar tools' finding, alert, or detection mechanism(s).
	DataSecurity *DataSecurity `json:"data_security,omitempty" parquet:"data_security,optional"`

	// Database: Describes the database where classified or sensitive data is stored in, or was accessed from. Databases are typically datastore services that contain an organized collection of structured and/or semi-structured data.
	Database *Database `json:"database,omitempty" parquet:"database,optional"`

	// Databucket: Describes the databucket where classified or sensitive data is stored in, or was accessed from. The data bucket object is a basic container that holds data, typically organized through the use of data partitions.
	Databucket *Databucket `json:"databucket,omitempty" parquet:"databucket,optional"`

	// Device: Describes the device where classified or sensitive data is stored in, or was accessed from.
	Device *Device `json:"device,omitempty" parquet:"device,optional"`

	// Disposition: The disposition name, normalized to the caption of the disposition_id value. In the case of 'Other', it is defined by the event source.
	Disposition *string `json:"disposition,omitempty" parquet:"disposition,optional"`

	// Disposition ID: Describes the outcome or action taken by a security control, such as access control checks, malware detections or various types of policy violations.
	DispositionId *int32 `json:"disposition_id,omitempty" parquet:"disposition_id,optional"`

	// Destination Endpoint: Describes the endpoint where classified or sensitive data is stored in, or was accessed from.
	DstEndpoint *NetworkEndpoint `json:"dst_endpoint,omitempty" parquet:"dst_endpoint,optional"`

	// Duration Milliseconds: The event duration or aggregate time, the amount of time the event covers from <code>start_time</code> to <code>end_time</code> in milliseconds.
	Duration *int64 `json:"duration,omitempty" parquet:"duration,optional"`

	// End Time: The time of the most recent event included in the finding.
	EndTime int64 `json:"end_time,omitempty" parquet:"end_time,timestamp_millis,timestamp(millisecond),optional"`

	// Enrichments: The additional information from an external data source, which is associated with the event or a finding. For example add location information for the IP address in the DNS answers:</p><code>[{"name": "answers.ip", "value": "92.24.47.250", "type": "location", "data": {"city": "Socotra", "continent": "Asia", "coordinates": [-25.4153, 17.0743], "country": "YE", "desc": "Yemen"}}]</code>
	Enrichments []Enrichment `json:"enrichments,omitempty" parquet:"enrichments,list,optional"`

	// File: Describes a file that contains classified or sensitive data.
	File *File `json:"file,omitempty" parquet:"file,optional"`

	// Finding Information: Describes the supporting information about a generated finding.
	FindingInfo FindingInformation `json:"finding_info" parquet:"finding_info"`

	// Firewall Rule: The firewall rule that pertains to the control that triggered the event, if applicable.
	FirewallRule *FirewallRule `json:"firewall_rule,omitempty" parquet:"firewall_rule,optional"`

	// Impact: The impact , normalized to the caption of the impact_id value. In the case of 'Other', it is defined by the event source.
	Impact *string `json:"impact,omitempty" parquet:"impact,optional"`

	// Impact ID: The normalized impact of the incident or finding. Per NIST, this is the magnitude of harm that can be expected to result from the consequences of unauthorized disclosure, modification, destruction, or loss of information or information system availability.
	ImpactId *int32 `json:"impact_id,omitempty" parquet:"impact_id,optional"`

	// Impact Score: The impact as an integer value of the finding, valid range 0-100.
	ImpactScore *int32 `json:"impact_score,omitempty" parquet:"impact_score,optional"`

	// Alert: Indicates that the event is considered to be an alertable signal. For example, an <code>activity_id</code> of 'Create' could constitute an alertable signal and the value would be <code>true</code>, while 'Close' likely would not and either omit the attribute or set its value to <code>false</code>.  Note that other events with the <code>security_control</code> profile may also be deemed alertable signals and may also carry <code>is_alert = true</code> attributes.
	IsAlert *bool `json:"is_alert,omitempty" parquet:"is_alert,optional"`

	// Suspected Breach: A determination based on analytics as to whether a potential breach was found.
	IsSuspectedBreach *bool `json:"is_suspected_breach,omitempty" parquet:"is_suspected_breach,optional"`

	// Malware: A list of Malware objects, describing details about the identified malware.
	Malware []Malware `json:"malware,omitempty" parquet:"malware,list,optional"`

	// Malware Scan Info: Describes details about the scan job that identified malware on the target system.
	MalwareScanInfo *MalwareScanInfo `json:"malware_scan_info,omitempty" parquet:"malware_scan_info,optional"`

	// Message: The description of the event/finding, as defined by the source.
	Message *string `json:"message,omitempty" parquet:"message,optional"`

	// Metadata: The metadata associated with the event or a finding.
	Metadata Metadata `json:"metadata" parquet:"metadata"`

	// Observables: The observables associated with the event or a finding.
	Observables []Observable `json:"observables,omitempty" parquet:"observables,list,optional"`

	// Policy: The policy that pertains to the control that triggered the event, if applicable. For example the name of an anti-malware policy or an access control policy.
	Policy *Policy `json:"policy,omitempty" parquet:"policy,optional"`

	// Priority: The priority, normalized to the caption of the priority_id value. In the case of 'Other', it is defined by the event source.
	Priority *string `json:"priority,omitempty" parquet:"priority,optional"`

	// Priority ID: The normalized priority. Priority identifies the relative importance of the incident or finding. It is a measurement of urgency.
	PriorityId *int32 `json:"priority_id,omitempty" parquet:"priority_id,optional"`

	// Raw Data: The raw event/finding data as received from the source.
	RawData *string `json:"raw_data,omitempty" parquet:"raw_data,optional"`

	// Raw Data Hash: The hash, which describes the content of the raw_data field.
	RawDataHash *Fingerprint `json:"raw_data_hash,omitempty" parquet:"raw_data_hash,optional"`

	// Raw Data Size: The size of the raw data which was transformed into an OCSF event, in bytes.
	RawDataSize *int64 `json:"raw_data_size,omitempty" parquet:"raw_data_size,optional"`

	// Additional Resources: Describes details about additional resources, where classified or sensitive data is stored in, or was accessed from. <p> You can populate this object, if the specific resource type objects available in the class (<code>database, databucket, table, file</code>) aren't sufficient; OR <br> You can also choose to duplicate <code>uid, name</code> of the specific resources objects, for a consistent access to resource uids across all findings.
	Resources []ResourceDetails `json:"resources,omitempty" parquet:"resources,list,optional"`

	// Risk Details: Describes the risk associated with the finding.
	RiskDetails *string `json:"risk_details,omitempty" parquet:"risk_details,optional"`

	// Risk Level: The risk level, normalized to the caption of the risk_level_id value.
	RiskLevel *string `json:"risk_level,omitempty" parquet:"risk_level,optional"`

	// Risk Level ID: The normalized risk level id.
	RiskLevelId *int32 `json:"risk_level_id,omitempty" parquet:"risk_level_id,optional"`

	// Risk Score: The risk score as reported by the event source.
	RiskScore *int32 `json:"risk_score,omitempty" parquet:"risk_score,optional"`

	// Severity: The event/finding severity, normalized to the caption of the <code>severity_id</code> value. In the case of 'Other', it is defined by the source.
	Severity *string `json:"severity,omitempty" parquet:"severity,optional"`

	// Severity ID: <p>The normalized identifier of the event/finding severity.</p>The normalized severity is a measurement the effort and expense required to manage and resolve an event or incident. Smaller numerical values represent lower impact events, and larger numerical values represent higher impact events.
	SeverityId int32 `json:"severity_id" parquet:"severity_id"`

	// Source Endpoint: Details about the source endpoint where classified or sensitive data was accessed from.
	SrcEndpoint *NetworkEndpoint `json:"src_endpoint,omitempty" parquet:"src_endpoint,optional"`

	// Source URL: A Url link used to access the original incident.
	SrcUrl *string `json:"src_url,omitempty" parquet:"src_url,optional"`

	// Start Time: The time of the least recent event included in the finding.
	StartTime int64 `json:"start_time,omitempty" parquet:"start_time,timestamp_millis,timestamp(millisecond),optional"`

	// Status: The normalized status of the Finding set by the consumer normalized to the caption of the status_id value. In the case of 'Other', it is defined by the source.
	Status *string `json:"status,omitempty" parquet:"status,optional"`

	// Status Code: The event status code, as reported by the event source.<br /><br />For example, in a Windows Failed Authentication event, this would be the value of 'Failure Code', e.g. 0x18.
	StatusCode *string `json:"status_code,omitempty" parquet:"status_code,optional"`

	// Status Detail: The status detail contains additional information about the event/finding outcome.
	StatusDetail *string `json:"status_detail,omitempty" parquet:"status_detail,optional"`

	// Status ID: The normalized status identifier of the Finding, set by the consumer.
	StatusId *int32 `json:"status_id,omitempty" parquet:"status_id,optional"`

	// Table: Describes the table where classified or sensitive data is stored in, or was accessed from. The table object represents a table within a structured relational database, warehouse, lake, or similar.
	Table *Table `json:"table,omitempty" parquet:"table,optional"`

	// Tickets: The associated ticket(s) in the ticketing system. Each ticket contains details like ticket ID, status, etc.
	Tickets []Ticket `json:"tickets,omitempty" parquet:"tickets,list,optional"`

	// Event Time: The normalized event occurrence time or the finding creation time.
	Time int64 `json:"time" parquet:"time,timestamp_millis,timestamp(millisecond)"`

	// Timezone Offset: The number of minutes that the reported event <code>time</code> is ahead or behind UTC, in the range -1,080 to +1,080.
	TimezoneOffset *int32 `json:"timezone_offset,omitempty" parquet:"timezone_offset,optional"`

	// Type Name: The event/finding type name, as defined by the type_uid.
	TypeName *string `json:"type_name,omitempty" parquet:"type_name,optional"`

	// Type ID: The event/finding type ID. It identifies the event's semantics and structure. The value is calculated by the logging system as: <code>class_uid * 100 + activity_id</code>.
	TypeUid int64 `json:"type_uid" parquet:"type_uid"`

	// Unmapped Data: The attributes that are not mapped to the event schema. The names and values of those attributes are specific to the event source.
	Unmapped *Object `json:"unmapped,omitempty" parquet:"unmapped,optional"`

	// Vendor Attributes: The Vendor Attributes object can be used to represent values of attributes populated by the Vendor/Finding Provider. It can help distinguish between the vendor-provided values and consumer-updated values, of key attributes like <code>severity_id</code>.<br>The original finding producer should not populate this object. It should be populated by consuming systems that support data mutability.
	VendorAttributes *VendorAttributes `json:"vendor_attributes,omitempty" parquet:"vendor_attributes,optional"`

	// Verdict: The verdict assigned to an Incident finding.
	Verdict *string `json:"verdict,omitempty" parquet:"verdict,optional"`

	// Verdict ID: The normalized verdict of an Incident.
	VerdictId *int32 `json:"verdict_id,omitempty" parquet:"verdict_id,optional"`
}

func (v *DataSecurityFinding) Observable() (*int, string) {
	return nil, ""
}

func (v *DataSecurityFinding) ValidateObservables() error {
	presentObservables := ocsf.PresentObservablesOf(v)
	for presObsIdx := range presentObservables {
		var found bool
		for obsIdx := range v.Observables {
			presObsEnum := presentObservables[presObsIdx][0].(*int)
			if v.Observables[obsIdx].TypeId == int32(*presObsEnum) {
				found = true
				break
			}
		}
		if !found {
			obs := presentObservables[presObsIdx]
			return fmt.Errorf("non-null observable %s(%d) not found in observables array", obs[1], *obs[0].(*int))
		}
	}
	return nil
}

var DataSecurityFindingFields = []arrow.Field{
	{Name: "action", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "action_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "activity_id", Type: arrow.PrimitiveTypes.Int32, Nullable: false},
	{Name: "activity_name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "actor", Type: ActorStruct, Nullable: true},
	{Name: "api", Type: APIStruct, Nullable: true},
	{Name: "assignee", Type: UserStruct, Nullable: true},
	{Name: "assignee_group", Type: GroupStruct, Nullable: true},
	{Name: "attacks", Type: arrow.ListOf(MITREATTCKATLASStruct), Nullable: true},
	{Name: "authorizations", Type: arrow.ListOf(AuthorizationResultStruct), Nullable: true},
	{Name: "category_name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "category_uid", Type: arrow.PrimitiveTypes.Int32, Nullable: false},
	{Name: "class_name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "class_uid", Type: arrow.PrimitiveTypes.Int32, Nullable: false},
	{Name: "comment", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "confidence", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "confidence_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "confidence_score", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "count", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "data_security", Type: DataSecurityStruct, Nullable: true},
	{Name: "database", Type: DatabaseStruct, Nullable: true},
	{Name: "databucket", Type: DatabucketStruct, Nullable: true},
	{Name: "device", Type: DeviceStruct, Nullable: true},
	{Name: "disposition", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "disposition_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "dst_endpoint", Type: NetworkEndpointStruct, Nullable: true},
	{Name: "duration", Type: arrow.PrimitiveTypes.Int64, Nullable: true},
	{Name: "end_time", Type: arrow.FixedWidthTypes.Timestamp_ms, Nullable: true},
	{Name: "enrichments", Type: arrow.ListOf(EnrichmentStruct), Nullable: true},
	{Name: "file", Type: FileStruct, Nullable: true},
	{Name: "finding_info", Type: FindingInformationStruct, Nullable: false},
	{Name: "firewall_rule", Type: FirewallRuleStruct, Nullable: true},
	{Name: "impact", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "impact_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "impact_score", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "is_alert", Type: arrow.FixedWidthTypes.Boolean, Nullable: true},
	{Name: "is_suspected_breach", Type: arrow.FixedWidthTypes.Boolean, Nullable: true},
	{Name: "malware", Type: arrow.ListOf(MalwareStruct), Nullable: true},
	{Name: "malware_scan_info", Type: MalwareScanInfoStruct, Nullable: true},
	{Name: "message", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "metadata", Type: MetadataStruct, Nullable: false},
	{Name: "observables", Type: arrow.ListOf(ObservableStruct), Nullable: true},
	{Name: "policy", Type: PolicyStruct, Nullable: true},
	{Name: "priority", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "priority_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "raw_data", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "raw_data_hash", Type: FingerprintStruct, Nullable: true},
	{Name: "raw_data_size", Type: arrow.PrimitiveTypes.Int64, Nullable: true},
	{Name: "resources", Type: arrow.ListOf(ResourceDetailsStruct), Nullable: true},
	{Name: "risk_details", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "risk_level", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "risk_level_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "risk_score", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "severity", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "severity_id", Type: arrow.PrimitiveTypes.Int32, Nullable: false},
	{Name: "src_endpoint", Type: NetworkEndpointStruct, Nullable: true},
	{Name: "src_url", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "start_time", Type: arrow.FixedWidthTypes.Timestamp_ms, Nullable: true},
	{Name: "status", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "status_code", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "status_detail", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "status_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "table", Type: TableStruct, Nullable: true},
	{Name: "tickets", Type: arrow.ListOf(TicketStruct), Nullable: true},
	{Name: "time", Type: arrow.FixedWidthTypes.Timestamp_ms, Nullable: false},
	{Name: "timezone_offset", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "type_name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "type_uid", Type: arrow.PrimitiveTypes.Int64, Nullable: false},
	{Name: "unmapped", Type: ObjectStruct, Nullable: true},
	{Name: "vendor_attributes", Type: VendorAttributesStruct, Nullable: true},
	{Name: "verdict", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "verdict_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
}

var DataSecurityFindingStruct = arrow.StructOf(DataSecurityFindingFields...)

var DataSecurityFindingSchema = arrow.NewSchema(DataSecurityFindingFields, nil)
var DataSecurityFindingClassname = "data_security_finding"
