// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type DigitalSignature struct {

	// Algorithm: The digital signature algorithm used to create the signature, normalized to the caption of 'algorithm_id'. In the case of 'Other', it is defined by the event source.
	Algorithm *string `json:"algorithm,omitempty" parquet:"algorithm,optional"`

	// Algorithm ID: The identifier of the normalized digital signature algorithm.
	AlgorithmId int32 `json:"algorithm_id" parquet:"algorithm_id"`

	// Certificate: The certificate object containing information about the digital certificate.
	Certificate *DigitalCertificate `json:"certificate,omitempty" parquet:"certificate,optional"`

	// Created Time: The time when the digital signature was created.
	CreatedTime int64 `json:"created_time,omitempty" parquet:"created_time,timestamp_millis,timestamp(millisecond),optional"`

	// Developer UID: The developer ID on the certificate that signed the file.
	DeveloperUid *string `json:"developer_uid,omitempty" parquet:"developer_uid,optional"`

	// Message Digest: The message digest attribute contains the fixed length message hash representation and the corresponding hashing algorithm information.
	Digest *Fingerprint `json:"digest,omitempty" parquet:"digest,optional"`

	// State: The digital signature state defines the signature state, normalized to the caption of 'state_id'. In the case of 'Other', it is defined by the event source.
	State *string `json:"state,omitempty" parquet:"state,optional"`

	// State ID: The normalized identifier of the signature state.
	StateId *int32 `json:"state_id,omitempty" parquet:"state_id,optional"`
}

func (v *DigitalSignature) Observable() (*int, string) {
	return nil, ""
}

var DigitalSignatureFields = []arrow.Field{
	{Name: "algorithm", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "algorithm_id", Type: arrow.PrimitiveTypes.Int32, Nullable: false},
	{Name: "certificate", Type: DigitalCertificateStruct, Nullable: true},
	{Name: "created_time", Type: arrow.FixedWidthTypes.Timestamp_ms, Nullable: true},
	{Name: "developer_uid", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "digest", Type: FingerprintStruct, Nullable: true},
	{Name: "state", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "state_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
}

var DigitalSignatureStruct = arrow.StructOf(DigitalSignatureFields...)

var DigitalSignatureSchema = arrow.NewSchema(DigitalSignatureFields, nil)
var DigitalSignatureClassname = "digital_signature"
