// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type DiscoveryDetails struct {

	// Count: The number of discovered entities of the specified type.
	Count *int32 `json:"count,omitempty" parquet:"count,optional"`

	// Occurrences: Details about where in the target entity, specified information was discovered. Only the attributes, relevant to the target entity type should be populated.
	Occurrences []OccurrenceDetails `json:"occurrences,omitempty" parquet:"occurrences,list,optional"`

	// Type: The specific type of information that was discovered. e.g.<code> name, phone_number, etc.</code>
	Type *string `json:"type,omitempty" parquet:"type,optional"`

	// Value: Optionally, the specific value of discovered information.
	Value *string `json:"value,omitempty" parquet:"value,optional"`
}

func (v *DiscoveryDetails) Observable() (*int, string) {
	return nil, ""
}

var DiscoveryDetailsFields = []arrow.Field{
	{Name: "count", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "occurrences", Type: arrow.ListOf(OccurrenceDetailsStruct), Nullable: true},
	{Name: "type", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "value", Type: arrow.BinaryTypes.String, Nullable: true},
}

var DiscoveryDetailsStruct = arrow.StructOf(DiscoveryDetailsFields...)

var DiscoveryDetailsSchema = arrow.NewSchema(DiscoveryDetailsFields, nil)
var DiscoveryDetailsClassname = "discovery_details"
