// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type Display struct {

	// Color Depth: The numeric color depth.
	ColorDepth *int32 `json:"color_depth,omitempty" parquet:"color_depth,optional"`

	// Physical Height: The numeric physical height of display.
	PhysicalHeight *int32 `json:"physical_height,omitempty" parquet:"physical_height,optional"`

	// Physical Orientation: The numeric physical orientation of display.
	PhysicalOrientation *int32 `json:"physical_orientation,omitempty" parquet:"physical_orientation,optional"`

	// Physical Width: The numeric physical width of display.
	PhysicalWidth *int32 `json:"physical_width,omitempty" parquet:"physical_width,optional"`

	// Scale Factor: The numeric scale factor of display.
	ScaleFactor *int32 `json:"scale_factor,omitempty" parquet:"scale_factor,optional"`
}

func (v *Display) Observable() (*int, string) {
	return nil, ""
}

var DisplayFields = []arrow.Field{
	{Name: "color_depth", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "physical_height", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "physical_orientation", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "physical_width", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "scale_factor", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
}

var DisplayStruct = arrow.StructOf(DisplayFields...)

var DisplaySchema = arrow.NewSchema(DisplayFields, nil)
var DisplayClassname = "display"
