// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type Email struct {

	// Cc: The machine-readable email header Cc values, as defined by RFC 5322. For example <code>example.user@usersdomain.com</code>.
	Cc []string `json:"cc,omitempty" parquet:"cc,list,optional"`

	// Cc Mailboxes: The human-readable email header Cc Mailbox values. For example <code>'Example User &lt;example.user@usersdomain.com&gt;'</code>.
	CcMailboxes []string `json:"cc_mailboxes,omitempty" parquet:"cc_mailboxes,list,optional"`

	// Data Classification: A list of Data Classification objects, that include information about data classification levels and data category types, identified by a classifier.
	DataClassifications []DataClassification `json:"data_classifications,omitempty" parquet:"data_classifications,list,optional"`

	// Delivered To List: The machine-readable <strong>Delivered-To</strong> email header values. For example <code>example.user@usersdomain.com</code>
	DeliveredToList []string `json:"delivered_to_list,omitempty" parquet:"delivered_to_list,list,optional"`

	// Files: The files embedded or attached to the email.
	Files []File `json:"files,omitempty" parquet:"files,list,optional"`

	// From: The machine-readable email header From value, as defined by RFC 5322. For example <code>example.user@usersdomain.com</code>.
	From *string `json:"from,omitempty" parquet:"from,optional"`

	// From List: The machine-readable email header From values. This array should contain the value in <code>from</code>. For example <code>example.user@usersdomain.com</code>.
	FromList []string `json:"from_list,omitempty" parquet:"from_list,list,optional"`

	// From Mailbox: The human-readable email header From Mailbox value. For example <code>'Example User &lt;example.user@usersdomain.com&gt;'</code>.
	FromMailbox *string `json:"from_mailbox,omitempty" parquet:"from_mailbox,optional"`

	// From Mailboxes: The human-readable email header From Mailbox values. This array should contain the value in <code>from_mailbox</code>. For example <code>'Example User &lt;example.user@usersdomain.com&gt;'</code>.
	FromMailboxes []string `json:"from_mailboxes,omitempty" parquet:"from_mailboxes,list,optional"`

	// HTTP Headers: Additional HTTP headers of an HTTP request or response.
	HttpHeaders []HTTPHeader `json:"http_headers,omitempty" parquet:"http_headers,list,optional"`

	// Read: The indication of whether the email has been read.
	IsRead *bool `json:"is_read,omitempty" parquet:"is_read,optional"`

	// Message UID: The email header Message-ID value, as defined by RFC 5322.
	MessageUid *string `json:"message_uid,omitempty" parquet:"message_uid,optional"`

	// Raw Header: The email authentication header.
	RawHeader *string `json:"raw_header,omitempty" parquet:"raw_header,optional"`

	// Reply To List: The machine-readable email header Reply-To values, as defined by RFC 5322. For example <code>example.user@usersdomain.com</code>
	ReplyToList []string `json:"reply_to_list,omitempty" parquet:"reply_to_list,list,optional"`

	// Reply To Mailboxes: The human-readable email header Reply To Mailbox values. For example <code>'Example User &lt;example.user@usersdomain.com&gt;'</code>.
	ReplyToMailboxes []string `json:"reply_to_mailboxes,omitempty" parquet:"reply_to_mailboxes,list,optional"`

	// Return Path: The address found in the 'Return-Path' header, which indicates where bounce messages (non-delivery reports) should be sent. This address is often set by the sending system and may differ from the 'From' or 'Sender' addresses. For example, <code>mailer-daemon@senderserver.com</code>.
	ReturnPath *string `json:"return_path,omitempty" parquet:"return_path,optional"`

	// Sender: The machine readable email address of the system or server that actually transmitted the email message, extracted from the email headers per RFC 5322. This differs from the <code>from</code> field, which shows the message author. The sender field is most commonly used when multiple addresses appear in the <code> from_list </code> field, or when the transmitting system is different from the message author (such as when sending on behalf of someone else).
	Sender *string `json:"sender,omitempty" parquet:"sender,optional"`

	// Sender Mailbox: The human readable email address of the system or server that actually transmitted the email message, extracted from the email headers per RFC 5322. This differs from the <code>from_mailbox</code> field, which shows the message author. The sender mailbox field is most commonly used when multiple addresses appear in the <code> from_mailboxes </code> field, or when the transmitting system is different from the message author (such as when sending on behalf of someone else).
	SenderMailbox *string `json:"sender_mailbox,omitempty" parquet:"sender_mailbox,optional"`

	// Size: The size in bytes of the email, including attachments.
	Size *int64 `json:"size,omitempty" parquet:"size,optional"`

	// Subject: The email header Subject value, as defined by RFC 5322.
	Subject *string `json:"subject,omitempty" parquet:"subject,optional"`

	// To: The machine-readable email header To values, as defined by RFC 5322. For example <code>example.user@usersdomain.com</code>
	To []string `json:"to,omitempty" parquet:"to,list,optional"`

	// To Mailboxes: The human-readable email header To Mailbox values. For example <code>'Example User &lt;example.user@usersdomain.com&gt;'</code>.
	ToMailboxes []string `json:"to_mailboxes,omitempty" parquet:"to_mailboxes,list,optional"`

	// Email Thread UID: The unique identifier of the email thread.
	Uid *string `json:"uid,omitempty" parquet:"uid,optional"`

	// URLs: The URLs embedded in the email.
	Urls []UniformResourceLocator `json:"urls,omitempty" parquet:"urls,list,optional"`

	// X-Originating-IP: The X-Originating-IP header identifying the emails originating IP address(es).
	XOriginatingIp []string `json:"x_originating_ip,omitempty" parquet:"x_originating_ip,list,optional"`
}

func (v *Email) Observable() (*int, string) {
	typeId := 22
	return &typeId, "email"
}

var EmailFields = []arrow.Field{
	{Name: "cc", Type: arrow.ListOf(arrow.BinaryTypes.String), Nullable: true},
	{Name: "cc_mailboxes", Type: arrow.ListOf(arrow.BinaryTypes.String), Nullable: true},
	{Name: "data_classifications", Type: arrow.ListOf(DataClassificationStruct), Nullable: true},
	{Name: "delivered_to_list", Type: arrow.ListOf(arrow.BinaryTypes.String), Nullable: true},
	{Name: "files", Type: arrow.ListOf(FileStruct), Nullable: true},
	{Name: "from", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "from_list", Type: arrow.ListOf(arrow.BinaryTypes.String), Nullable: true},
	{Name: "from_mailbox", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "from_mailboxes", Type: arrow.ListOf(arrow.BinaryTypes.String), Nullable: true},
	{Name: "http_headers", Type: arrow.ListOf(HTTPHeaderStruct), Nullable: true},
	{Name: "is_read", Type: arrow.FixedWidthTypes.Boolean, Nullable: true},
	{Name: "message_uid", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "raw_header", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "reply_to_list", Type: arrow.ListOf(arrow.BinaryTypes.String), Nullable: true},
	{Name: "reply_to_mailboxes", Type: arrow.ListOf(arrow.BinaryTypes.String), Nullable: true},
	{Name: "return_path", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "sender", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "sender_mailbox", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "size", Type: arrow.PrimitiveTypes.Int64, Nullable: true},
	{Name: "subject", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "to", Type: arrow.ListOf(arrow.BinaryTypes.String), Nullable: true},
	{Name: "to_mailboxes", Type: arrow.ListOf(arrow.BinaryTypes.String), Nullable: true},
	{Name: "uid", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "urls", Type: arrow.ListOf(UniformResourceLocatorStruct), Nullable: true},
	{Name: "x_originating_ip", Type: arrow.ListOf(arrow.BinaryTypes.String), Nullable: true},
}

var EmailStruct = arrow.StructOf(EmailFields...)

var EmailSchema = arrow.NewSchema(EmailFields, nil)
var EmailClassname = "email"
