// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type EPSS struct {

	// Created Time: The timestamp indicating when the EPSS score was calculated.
	CreatedTime int64 `json:"created_time,omitempty" parquet:"created_time,timestamp_millis,timestamp(millisecond),optional"`

	// EPSS Percentile: The EPSS score's percentile representing relative importance and ranking of the score in the larger EPSS dataset.
	Percentile *float64 `json:"percentile,omitempty" parquet:"percentile,optional"`

	// EPPS Score: The EPSS score representing the probability [0-1] of exploitation in the wild in the next 30 days (following score publication).
	Score string `json:"score" parquet:"score"`

	// Version: The version of the EPSS model used to calculate the score.
	Version *string `json:"version,omitempty" parquet:"version,optional"`
}

func (v *EPSS) Observable() (*int, string) {
	return nil, ""
}

var EPSSFields = []arrow.Field{
	{Name: "created_time", Type: arrow.FixedWidthTypes.Timestamp_ms, Nullable: true},
	{Name: "percentile", Type: arrow.PrimitiveTypes.Float64, Nullable: true},
	{Name: "score", Type: arrow.BinaryTypes.String, Nullable: false},
	{Name: "version", Type: arrow.BinaryTypes.String, Nullable: true},
}

var EPSSStruct = arrow.StructOf(EPSSFields...)

var EPSSSchema = arrow.NewSchema(EPSSFields, nil)
var EPSSClassname = "epss"
