// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type EvidenceArtifacts struct {

	// Actor: Describes details about the user/role/process that was the source of the activity that triggered the detection.
	Actor *Actor `json:"actor,omitempty" parquet:"actor,optional"`

	// API Details: Describes details about the API call associated to the activity that triggered the detection.
	Api *API `json:"api,omitempty" parquet:"api,optional"`

	// Connection Info: Describes details about the network connection associated to the activity that triggered the detection.
	ConnectionInfo *NetworkConnectionInformation `json:"connection_info,omitempty" parquet:"connection_info,optional"`

	// Container: Describes details about the container associated to the activity that triggered the detection.
	Container *Container `json:"container,omitempty" parquet:"container,optional"`

	// Data: Additional evidence data that is not accounted for in the specific evidence attributes.<code> Use only when absolutely necessary.</code>
	Data *string `json:"data,omitempty" parquet:"data,optional"`

	// Database: Describes details about the database associated to the activity that triggered the detection.
	Database *Database `json:"database,omitempty" parquet:"database,optional"`

	// Databucket: Describes details about the databucket associated to the activity that triggered the detection.
	Databucket *Databucket `json:"databucket,omitempty" parquet:"databucket,optional"`

	// Device: An addressable device, computer system or host associated to the activity that triggered the detection.
	Device *Device `json:"device,omitempty" parquet:"device,optional"`

	// Destination Endpoint: Describes details about the destination of the network activity that triggered the detection.
	DstEndpoint *NetworkEndpoint `json:"dst_endpoint,omitempty" parquet:"dst_endpoint,optional"`

	// Email: The email object associated to the activity that triggered the detection.
	Email *Email `json:"email,omitempty" parquet:"email,optional"`

	// File: Describes details about the file associated to the activity that triggered the detection.
	File *File `json:"file,omitempty" parquet:"file,optional"`

	// HTTP Request: Describes details about the http request associated to the activity that triggered the detection.
	HttpRequest *HTTPRequest `json:"http_request,omitempty" parquet:"http_request,optional"`

	// HTTP Response: Describes details about the http response associated to the activity that triggered the detection.
	HttpResponse *HTTPResponse `json:"http_response,omitempty" parquet:"http_response,optional"`

	// JA4+ Fingerprints: Describes details about the JA4+ fingerprints that triggered the detection.
	Ja4FingerprintList []JA4Fingerprint `json:"ja4_fingerprint_list,omitempty" parquet:"ja4_fingerprint_list,list,optional"`

	// Job: Describes details about the scheduled job that was associated with the activity that triggered the detection.
	Job *Job `json:"job,omitempty" parquet:"job,optional"`

	// Name: The naming convention or type identifier of the evidence associated with the security detection. For example, the <code>@odata.type</code> from Microsoft Graph Alerts V2 or <code>display_name</code> from CrowdStrike Falcon Incident Behaviors.
	Name *string `json:"name,omitempty" parquet:"name,optional"`

	// Process: Describes details about the process associated to the activity that triggered the detection.
	Process *Process `json:"process,omitempty" parquet:"process,optional"`

	// DNS Query: Describes details about the DNS query associated to the activity that triggered the detection.
	Query *DNSQuery `json:"query,omitempty" parquet:"query,optional"`

	// Registry Key: Describes details about the registry key that triggered the detection.
	RegKey *RegistryKey `json:"reg_key,omitempty" parquet:"reg_key,optional"`

	// Registry Value: Describes details about the registry value that triggered the detection.
	RegValue *RegistryValue `json:"reg_value,omitempty" parquet:"reg_value,optional"`

	// Cloud Resources: Describes details about the cloud resources directly related to activity that triggered the detection. For resources impacted by the detection, use <code>Affected Resources</code> at the top-level of the finding.
	Resources []ResourceDetails `json:"resources,omitempty" parquet:"resources,list,optional"`

	// Script: Describes details about the script that was associated with the activity that triggered the detection.
	Script *Script `json:"script,omitempty" parquet:"script,optional"`

	// Source Endpoint: Describes details about the source of the network activity that triggered the detection.
	SrcEndpoint *NetworkEndpoint `json:"src_endpoint,omitempty" parquet:"src_endpoint,optional"`

	// TLS: Describes details about the Transport Layer Security (TLS) activity that triggered the detection.
	Tls *TransportLayerSecurityTLS `json:"tls,omitempty" parquet:"tls,optional"`

	// Unique ID: The unique identifier of the evidence associated with the security detection. For example, the <code>activity_id</code> from CrowdStrike Falcon Alerts or <code>behavior_id</code> from CrowdStrike Falcon Incident Behaviors.
	Uid *string `json:"uid,omitempty" parquet:"uid,optional"`

	// URL: The URL object that pertains to the event or object associated to the activity that triggered the detection.
	Url *UniformResourceLocator `json:"url,omitempty" parquet:"url,optional"`

	// User: Describes details about the user that was the target or somehow else associated with the activity that triggered the detection.
	User *User `json:"user,omitempty" parquet:"user,optional"`

	// Verdict: The normalized verdict of the evidence associated with the security detection.
	Verdict *string `json:"verdict,omitempty" parquet:"verdict,optional"`

	// Verdict ID: The normalized verdict (or status) ID of the evidence associated with the security detection. For example, Microsoft Graph Security Alerts contain a <code>verdict</code> enumeration for each type of <code>evidence</code> associated with the Alert. This is typically set by an automated investigation process or an analyst/investigator assigned to the finding.
	VerdictId *int32 `json:"verdict_id,omitempty" parquet:"verdict_id,optional"`

	// Windows Service: Describes details about the Windows service that triggered the detection.
	WinService *WindowsService `json:"win_service,omitempty" parquet:"win_service,optional"`
}

func (v *EvidenceArtifacts) Observable() (*int, string) {
	return nil, ""
}

var EvidenceArtifactsFields = []arrow.Field{
	{Name: "actor", Type: ActorStruct, Nullable: true},
	{Name: "api", Type: APIStruct, Nullable: true},
	{Name: "connection_info", Type: NetworkConnectionInformationStruct, Nullable: true},
	{Name: "container", Type: ContainerStruct, Nullable: true},
	{Name: "data", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "database", Type: DatabaseStruct, Nullable: true},
	{Name: "databucket", Type: DatabucketStruct, Nullable: true},
	{Name: "device", Type: DeviceStruct, Nullable: true},
	{Name: "dst_endpoint", Type: NetworkEndpointStruct, Nullable: true},
	{Name: "email", Type: EmailStruct, Nullable: true},
	{Name: "file", Type: FileStruct, Nullable: true},
	{Name: "http_request", Type: HTTPRequestStruct, Nullable: true},
	{Name: "http_response", Type: HTTPResponseStruct, Nullable: true},
	{Name: "ja4_fingerprint_list", Type: arrow.ListOf(JA4FingerprintStruct), Nullable: true},
	{Name: "job", Type: JobStruct, Nullable: true},
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "process", Type: ProcessStruct, Nullable: true},
	{Name: "query", Type: DNSQueryStruct, Nullable: true},
	{Name: "reg_key", Type: RegistryKeyStruct, Nullable: true},
	{Name: "reg_value", Type: RegistryValueStruct, Nullable: true},
	{Name: "resources", Type: arrow.ListOf(ResourceDetailsStruct), Nullable: true},
	{Name: "script", Type: ScriptStruct, Nullable: true},
	{Name: "src_endpoint", Type: NetworkEndpointStruct, Nullable: true},
	{Name: "tls", Type: TransportLayerSecurityTLSStruct, Nullable: true},
	{Name: "uid", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "url", Type: UniformResourceLocatorStruct, Nullable: true},
	{Name: "user", Type: UserStruct, Nullable: true},
	{Name: "verdict", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "verdict_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "win_service", Type: WindowsServiceStruct, Nullable: true},
}

var EvidenceArtifactsStruct = arrow.StructOf(EvidenceArtifactsFields...)

var EvidenceArtifactsSchema = arrow.NewSchema(EvidenceArtifactsFields, nil)
var EvidenceArtifactsClassname = "evidences"
