// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type SchemaExtension struct {

	// Name: The schema extension name. For example: <code>dev</code>.
	Name *string `json:"name,omitempty" parquet:"name,optional"`

	// Unique ID: The schema extension unique identifier. For example: <code>999</code>.
	Uid *string `json:"uid,omitempty" parquet:"uid,optional"`

	// Version: The schema extension version. For example: <code>1.0.0-alpha.2</code>.
	Version string `json:"version" parquet:"version"`
}

func (v *SchemaExtension) Observable() (*int, string) {
	return nil, ""
}

var SchemaExtensionFields = []arrow.Field{
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "uid", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "version", Type: arrow.BinaryTypes.String, Nullable: false},
}

var SchemaExtensionStruct = arrow.StructOf(SchemaExtensionFields...)

var SchemaExtensionSchema = arrow.NewSchema(SchemaExtensionFields, nil)
var SchemaExtensionClassname = "extension"
