// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type Feature struct {

	// Name: The name of the feature.
	Name *string `json:"name,omitempty" parquet:"name,optional"`

	// Unique ID: The unique identifier of the feature.
	Uid *string `json:"uid,omitempty" parquet:"uid,optional"`

	// Version: The version of the feature.
	Version *string `json:"version,omitempty" parquet:"version,optional"`
}

func (v *Feature) Observable() (*int, string) {
	return nil, ""
}

var FeatureFields = []arrow.Field{
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "uid", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "version", Type: arrow.BinaryTypes.String, Nullable: true},
}

var FeatureStruct = arrow.StructOf(FeatureFields...)

var FeatureSchema = arrow.NewSchema(FeatureFields, nil)
var FeatureClassname = "feature"
