// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type FunctionInvocation struct {

	// Error Code: The error indication returned from the function. This may differ from the return value (e.g. when <code>errno</code> is used).
	Error *string `json:"error,omitempty" parquet:"error,optional"`

	// Parameters: The parameters passed into a function invocation.
	Parameters []Parameter `json:"parameters,omitempty" parquet:"parameters,list,optional"`

	// Return Value: The value returned from a function.
	ReturnValue *string `json:"return_value,omitempty" parquet:"return_value,optional"`
}

func (v *FunctionInvocation) Observable() (*int, string) {
	return nil, ""
}

var FunctionInvocationFields = []arrow.Field{
	{Name: "error", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "parameters", Type: arrow.ListOf(ParameterStruct), Nullable: true},
	{Name: "return_value", Type: arrow.BinaryTypes.String, Nullable: true},
}

var FunctionInvocationStruct = arrow.StructOf(FunctionInvocationFields...)

var FunctionInvocationSchema = arrow.NewSchema(FunctionInvocationFields, nil)
var FunctionInvocationClassname = "function_invocation"
