// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type HASSH struct {

	// Algorithm: The concatenation of key exchange, encryption, authentication and compression algorithms (separated by ';'). NOTE: This is not the underlying algorithm for the hash implementation.
	Algorithm *string `json:"algorithm,omitempty" parquet:"algorithm,optional"`

	// Fingerprint: The hash of the key exchange, encryption, authentication and compression algorithms.
	Fingerprint Fingerprint `json:"fingerprint" parquet:"fingerprint"`
}

func (v *HASSH) Observable() (*int, string) {
	return nil, ""
}

var HASSHFields = []arrow.Field{
	{Name: "algorithm", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "fingerprint", Type: FingerprintStruct, Nullable: false},
}

var HASSHStruct = arrow.StructOf(HASSHFields...)

var HASSHSchema = arrow.NewSchema(HASSHFields, nil)
var HASSHClassname = "hassh"
