// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type HTTPHeader struct {

	// Name: The name of the HTTP header.
	Name string `json:"name" parquet:"name"`

	// Value: The value of the HTTP header.
	Value string `json:"value" parquet:"value"`
}

func (v *HTTPHeader) Observable() (*int, string) {
	return nil, ""
}

var HTTPHeaderFields = []arrow.Field{
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: false},
	{Name: "value", Type: arrow.BinaryTypes.String, Nullable: false},
}

var HTTPHeaderStruct = arrow.StructOf(HTTPHeaderFields...)

var HTTPHeaderSchema = arrow.NewSchema(HTTPHeaderFields, nil)
var HTTPHeaderClassname = "http_header"
