// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type Job struct {

	// Command Line: The job command line.
	CmdLine *string `json:"cmd_line,omitempty" parquet:"cmd_line,optional"`

	// Created Time: The time when the job was created.
	CreatedTime int64 `json:"created_time,omitempty" parquet:"created_time,timestamp_millis,timestamp(millisecond),optional"`

	// Description: The description of the job.
	Desc *string `json:"desc,omitempty" parquet:"desc,optional"`

	// File: The file that pertains to the job.
	File *File `json:"file,omitempty" parquet:"file,optional"`

	// Last Run: The time when the job was last run.
	LastRunTime int64 `json:"last_run_time,omitempty" parquet:"last_run_time,timestamp_millis,timestamp(millisecond),optional"`

	// Name: The name of the job.
	Name string `json:"name" parquet:"name"`

	// Next Run: The time when the job will next be run.
	NextRunTime int64 `json:"next_run_time,omitempty" parquet:"next_run_time,timestamp_millis,timestamp(millisecond),optional"`

	// Run State: The run state of the job.
	RunState *string `json:"run_state,omitempty" parquet:"run_state,optional"`

	// Run State ID: The run state ID of the job.
	RunStateId *int32 `json:"run_state_id,omitempty" parquet:"run_state_id,optional"`

	// User: The user that created the job.
	User *User `json:"user,omitempty" parquet:"user,optional"`
}

func (v *Job) Observable() (*int, string) {
	return nil, ""
}

var JobFields = []arrow.Field{
	{Name: "cmd_line", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "created_time", Type: arrow.FixedWidthTypes.Timestamp_ms, Nullable: true},
	{Name: "desc", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "file", Type: FileStruct, Nullable: true},
	{Name: "last_run_time", Type: arrow.FixedWidthTypes.Timestamp_ms, Nullable: true},
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: false},
	{Name: "next_run_time", Type: arrow.FixedWidthTypes.Timestamp_ms, Nullable: true},
	{Name: "run_state", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "run_state_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "user", Type: UserStruct, Nullable: true},
}

var JobStruct = arrow.StructOf(JobFields...)

var JobSchema = arrow.NewSchema(JobFields, nil)
var JobClassname = "job"
