// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type KernelResource struct {

	// System: The indication of whether the object is part of the operating system.
	IsSystem *bool `json:"is_system,omitempty" parquet:"is_system,optional"`

	// Name: The name of the kernel resource.
	Name string `json:"name" parquet:"name"`

	// Path: The full path of the kernel resource.
	Path *string `json:"path,omitempty" parquet:"path,optional"`

	// System Call: The system call that was invoked.
	SystemCall *string `json:"system_call,omitempty" parquet:"system_call,optional"`

	// Type: The type of the kernel resource.
	Type *string `json:"type,omitempty" parquet:"type,optional"`

	// Type ID: The type of the kernel resource.
	TypeId int32 `json:"type_id" parquet:"type_id"`
}

func (v *KernelResource) Observable() (*int, string) {
	return nil, ""
}

var KernelResourceFields = []arrow.Field{
	{Name: "is_system", Type: arrow.FixedWidthTypes.Boolean, Nullable: true},
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: false},
	{Name: "path", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "system_call", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "type", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "type_id", Type: arrow.PrimitiveTypes.Int32, Nullable: false},
}

var KernelResourceStruct = arrow.StructOf(KernelResourceFields...)

var KernelResourceSchema = arrow.NewSchema(KernelResourceFields, nil)
var KernelResourceClassname = "kernel"
