// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type KernelExtension struct {

	// File: The driver/extension file object.
	File File `json:"file" parquet:"file"`
}

func (v *KernelExtension) Observable() (*int, string) {
	return nil, ""
}

var KernelExtensionFields = []arrow.Field{
	{Name: "file", Type: FileStruct, Nullable: false},
}

var KernelExtensionStruct = arrow.StructOf(KernelExtensionFields...)

var KernelExtensionSchema = arrow.NewSchema(KernelExtensionFields, nil)
var KernelExtensionClassname = "kernel_driver"
