// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type KeyValueobject struct {

	// Name: The name of the key.
	Name string `json:"name" parquet:"name"`

	// Value: The value associated to the key.
	Value *string `json:"value,omitempty" parquet:"value,optional"`

	// Values: Optional, the values associated to the key. You can populate this attribute, when you have multiple values for the same key.
	Values []string `json:"values,omitempty" parquet:"values,list,optional"`
}

func (v *KeyValueobject) Observable() (*int, string) {
	return nil, ""
}

var KeyValueobjectFields = []arrow.Field{
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: false},
	{Name: "value", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "values", Type: arrow.ListOf(arrow.BinaryTypes.String), Nullable: true},
}

var KeyValueobjectStruct = arrow.StructOf(KeyValueobjectFields...)

var KeyValueobjectSchema = arrow.NewSchema(KeyValueobjectFields, nil)
var KeyValueobjectClassname = "key_value_object"
