// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type Logger struct {

	// Device: The device where the events are logged.
	Device *Device `json:"device,omitempty" parquet:"device,optional"`

	// Event UID: The unique identifier of the event assigned by the logger.
	EventUid *string `json:"event_uid,omitempty" parquet:"event_uid,optional"`

	// Is Truncated: Indicates whether the OCSF event data has been truncated due to size limitations. When <code>true</code>, some event data may have been omitted to fit within system constraints.
	IsTruncated *bool `json:"is_truncated,omitempty" parquet:"is_truncated,optional"`

	// Log Format: The format of data in the log. For example JSON, syslog or CSV.
	LogFormat *string `json:"log_format,omitempty" parquet:"log_format,optional"`

	// Log Level: The level at which an event was logged. This can be log provider specific. For example the audit level.
	LogLevel *string `json:"log_level,omitempty" parquet:"log_level,optional"`

	// Log Name: The log name for the logging provider log, or the file name of the system log. This may be an intermediate store-and-forward log or a vendor destination log. For example /archive/server1/var/log/messages.0 or /var/log/.
	LogName *string `json:"log_name,omitempty" parquet:"log_name,optional"`

	// Log Provider: The logging provider or logging service that logged the event. This may be an intermediate application store-and-forward log or a vendor destination log.
	LogProvider *string `json:"log_provider,omitempty" parquet:"log_provider,optional"`

	// Log Version: The event log schema version of the original event. For example the syslog version or the Cisco Log Schema version
	LogVersion *string `json:"log_version,omitempty" parquet:"log_version,optional"`

	// Logged Time: <p>The time when the logging system collected and logged the event.</p>This attribute is distinct from the event time in that event time typically contain the time extracted from the original event. Most of the time, these two times will be different.
	LoggedTime int64 `json:"logged_time,omitempty" parquet:"logged_time,timestamp_millis,timestamp(millisecond),optional"`

	// Name: The name of the logging product instance.
	Name *string `json:"name,omitempty" parquet:"name,optional"`

	// Product: The product logging the event.  This may be the event source product, a management server product, a scanning product, a SIEM, etc.
	Product *Product `json:"product,omitempty" parquet:"product,optional"`

	// Transmission Time: The time when the event was transmitted from the logging device to it's next destination.
	TransmitTime int64 `json:"transmit_time,omitempty" parquet:"transmit_time,timestamp_millis,timestamp(millisecond),optional"`

	// Unique ID: The unique identifier of the logging product instance.
	Uid *string `json:"uid,omitempty" parquet:"uid,optional"`

	// Untruncated Size: The original size of the OCSF event data in kilobytes before any truncation occurred. This field is typically populated when <code>is_truncated</code> is <code>true</code> to indicate the full size of the original event.
	UntruncatedSize *int32 `json:"untruncated_size,omitempty" parquet:"untruncated_size,optional"`

	// Version: The version of the logging provider.
	Version *string `json:"version,omitempty" parquet:"version,optional"`
}

func (v *Logger) Observable() (*int, string) {
	return nil, ""
}

var LoggerFields = []arrow.Field{
	{Name: "device", Type: DeviceStruct, Nullable: true},
	{Name: "event_uid", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "is_truncated", Type: arrow.FixedWidthTypes.Boolean, Nullable: true},
	{Name: "log_format", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "log_level", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "log_name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "log_provider", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "log_version", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "logged_time", Type: arrow.FixedWidthTypes.Timestamp_ms, Nullable: true},
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "product", Type: ProductStruct, Nullable: true},
	{Name: "transmit_time", Type: arrow.FixedWidthTypes.Timestamp_ms, Nullable: true},
	{Name: "uid", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "untruncated_size", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "version", Type: arrow.BinaryTypes.String, Nullable: true},
}

var LoggerStruct = arrow.StructOf(LoggerFields...)

var LoggerSchema = arrow.NewSchema(LoggerFields, nil)
var LoggerClassname = "logger"
