// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type LongString struct {

	// Is Truncated: Indicates that <code>value</code> has been truncated. May be omitted if truncation has not occurred.
	IsTruncated *bool `json:"is_truncated,omitempty" parquet:"is_truncated,optional"`

	// Untruncated Size: The size in bytes of the string represented by <code>value</code> before truncation. Should be omitted if truncation has not occurred.
	UntruncatedSize *int32 `json:"untruncated_size,omitempty" parquet:"untruncated_size,optional"`

	// Value: The string value, truncated if <code>is_truncated</code> is <code>true</code>.
	Value string `json:"value" parquet:"value"`
}

func (v *LongString) Observable() (*int, string) {
	return nil, ""
}

var LongStringFields = []arrow.Field{
	{Name: "is_truncated", Type: arrow.FixedWidthTypes.Boolean, Nullable: true},
	{Name: "untruncated_size", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "value", Type: arrow.BinaryTypes.String, Nullable: false},
}

var LongStringStruct = arrow.StructOf(LongStringFields...)

var LongStringSchema = arrow.NewSchema(LongStringFields, nil)
var LongStringClassname = "long_string"
