// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type Metadata struct {

	// Correlation UID: A unique identifier used to correlate this OCSF event with other related OCSF events, distinct from the event's <code>uid</code> value. This enables linking multiple OCSF events that are part of the same activity, transaction, or security incident across different systems or time periods.
	CorrelationUid *string `json:"correlation_uid,omitempty" parquet:"correlation_uid,optional"`

	// Data Classification: A list of Data Classification objects, that include information about data classification levels and data category types, identified by a classifier.
	DataClassifications []DataClassification `json:"data_classifications,omitempty" parquet:"data_classifications,list,optional"`

	// Debug Information: Debug information about non-fatal issues with this OCSF event. Each issue is a line in this string array.
	Debug []string `json:"debug,omitempty" parquet:"debug,list,optional"`

	// Event Code: The identifier of the original event. For example the numerical Windows Event Code or Cisco syslog code.
	EventCode *string `json:"event_code,omitempty" parquet:"event_code,optional"`

	// Schema Extensions: The schema extensions used to create the event.
	Extensions []SchemaExtension `json:"extensions,omitempty" parquet:"extensions,list,optional"`

	// Is Truncated: Indicates whether the OCSF event data has been truncated due to size limitations. When <code>true</code>, some event data may have been omitted to fit within system constraints.
	IsTruncated *bool `json:"is_truncated,omitempty" parquet:"is_truncated,optional"`

	// Labels: The list of labels attached to the event. For example: <code>["sample", "dev"]</code>
	Labels []string `json:"labels,omitempty" parquet:"labels,list,optional"`

	// Log Source Format: The format of data in the log where the data originated. For example CSV, XML, Windows Multiline, JSON, syslog or Cisco Log Schema.
	LogFormat *string `json:"log_format,omitempty" parquet:"log_format,optional"`

	// Log Level: The level at which an event was logged. This can be log provider specific. For example the audit level.
	LogLevel *string `json:"log_level,omitempty" parquet:"log_level,optional"`

	// Log Name: The event log name, typically for the consumer of the event. For example, the storage bucket name, SIEM repository index name, etc.
	LogName *string `json:"log_name,omitempty" parquet:"log_name,optional"`

	// Log Provider: The logging provider or logging service that logged the event. For example AWS CloudWatch or Splunk.
	LogProvider *string `json:"log_provider,omitempty" parquet:"log_provider,optional"`

	// Log Source: The log system or component where the data originated. For example, a file path, syslog server name or a Windows hostname and logging subsystem such as Security.
	LogSource *string `json:"log_source,omitempty" parquet:"log_source,optional"`

	// Log Version: The event log schema version of the original event. For example the syslog version or the Cisco Log Schema version
	LogVersion *string `json:"log_version,omitempty" parquet:"log_version,optional"`

	// Logged Time: <p>The time when the logging system collected and logged the event.</p>This attribute is distinct from the event time in that event time typically contain the time extracted from the original event. Most of the time, these two times will be different.
	LoggedTime int64 `json:"logged_time,omitempty" parquet:"logged_time,timestamp_millis,timestamp(millisecond),optional"`

	// Loggers: An array of Logger objects that describe the pipeline of devices and logging products between the event source and its eventual destination. Note, this attribute can be used when there is a complex end-to-end path of event flow and/or to track the chain of custody of the data.
	Loggers []Logger `json:"loggers,omitempty" parquet:"loggers,list,optional"`

	// Modified Time: The time when the event was last modified or enriched.
	ModifiedTime int64 `json:"modified_time,omitempty" parquet:"modified_time,timestamp_millis,timestamp(millisecond),optional"`

	// Original Event ID: The unique identifier assigned to the event in its original logging system before transformation to OCSF format. This field preserves the source system's native event identifier, enabling traceability back to the raw log entry. For example, a Windows Event Record ID, a syslog message ID, a Splunk _cd value, or a database transaction log sequence number.
	OriginalEventUid *string `json:"original_event_uid,omitempty" parquet:"original_event_uid,optional"`

	// Original Time: The original event time as reported by the event source. For example, the time in the original format from system event log such as Syslog on Unix/Linux and the System event file on Windows. Omit if event is generated instead of collected via logs.
	OriginalTime *string `json:"original_time,omitempty" parquet:"original_time,optional"`

	// Processed Time: The event processed time, such as an ETL operation.
	ProcessedTime int64 `json:"processed_time,omitempty" parquet:"processed_time,timestamp_millis,timestamp(millisecond),optional"`

	// Product: The product that reported the event.
	Product Product `json:"product" parquet:"product"`

	// Profiles: The list of profiles used to create the event.  Profiles should be referenced by their <code>name</code> attribute for core profiles, or <code>extension/name</code> for profiles from extensions.
	Profiles []string `json:"profiles,omitempty" parquet:"profiles,list,optional"`

	// Reporter: The entity from which the event or finding was first reported.
	Reporter *Reporter `json:"reporter,omitempty" parquet:"reporter,optional"`

	// Sequence Number: Sequence number of the event. The sequence number is a value available in some events, to make the exact ordering of events unambiguous, regardless of the event time precision.
	Sequence *int32 `json:"sequence,omitempty" parquet:"sequence,optional"`

	// Source: The source of the event or finding. This can be any distinguishing name for the logical origin of the data — for example, 'CloudTrail Events', or a use case like 'Attack Simulations' or 'Vulnerability Scans'.
	Source *string `json:"source,omitempty" parquet:"source,optional"`

	// Tags: The list of tags; <code>{key:value}</code> pairs associated to the event.
	Tags []KeyValueobject `json:"tags,omitempty" parquet:"tags,list,optional"`

	// Tenant UID: The unique tenant identifier.
	TenantUid *string `json:"tenant_uid,omitempty" parquet:"tenant_uid,optional"`

	// Transformation Info: An array of transformation info that describes the mappings or transforms applied to the data.
	TransformationInfoList []TransformationInfo `json:"transformation_info_list,omitempty" parquet:"transformation_info_list,list,optional"`

	// Transmission Time: The time when the event was transmitted from the logging device to it's next destination.
	TransmitTime int64 `json:"transmit_time,omitempty" parquet:"transmit_time,timestamp_millis,timestamp(millisecond),optional"`

	// Type: The type of the event or finding as a subset of the <code>source</code> of the event. This can be any distinguishing characteristic of the data. For example 'Management Events' or 'Device Penetration Test'.
	Type *string `json:"type,omitempty" parquet:"type,optional"`

	// Event UID: A unique identifier assigned to the OCSF event. This ID is specific to the OCSF event itself and is distinct from the original event identifier in the source system (see <code>original_event_uid</code>).
	Uid *string `json:"uid,omitempty" parquet:"uid,optional"`

	// Untruncated Size: The original size of the OCSF event data in kilobytes before any truncation occurred. This field is typically populated when <code>is_truncated</code> is <code>true</code> to indicate the full size of the original event.
	UntruncatedSize *int32 `json:"untruncated_size,omitempty" parquet:"untruncated_size,optional"`

	// Version: The version of the OCSF schema, using Semantic Versioning Specification (<a target='_blank' href='https://semver.org'>SemVer</a>). For example: <code>1.0.0.</code> Event consumers use the version to determine the available event attributes.
	Version string `json:"version" parquet:"version"`
}

func (v *Metadata) Observable() (*int, string) {
	return nil, ""
}

var MetadataFields = []arrow.Field{
	{Name: "correlation_uid", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "data_classifications", Type: arrow.ListOf(DataClassificationStruct), Nullable: true},
	{Name: "debug", Type: arrow.ListOf(arrow.BinaryTypes.String), Nullable: true},
	{Name: "event_code", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "extensions", Type: arrow.ListOf(SchemaExtensionStruct), Nullable: true},
	{Name: "is_truncated", Type: arrow.FixedWidthTypes.Boolean, Nullable: true},
	{Name: "labels", Type: arrow.ListOf(arrow.BinaryTypes.String), Nullable: true},
	{Name: "log_format", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "log_level", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "log_name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "log_provider", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "log_source", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "log_version", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "logged_time", Type: arrow.FixedWidthTypes.Timestamp_ms, Nullable: true},
	{Name: "loggers", Type: arrow.ListOf(LoggerStruct), Nullable: true},
	{Name: "modified_time", Type: arrow.FixedWidthTypes.Timestamp_ms, Nullable: true},
	{Name: "original_event_uid", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "original_time", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "processed_time", Type: arrow.FixedWidthTypes.Timestamp_ms, Nullable: true},
	{Name: "product", Type: ProductStruct, Nullable: false},
	{Name: "profiles", Type: arrow.ListOf(arrow.BinaryTypes.String), Nullable: true},
	{Name: "reporter", Type: ReporterStruct, Nullable: true},
	{Name: "sequence", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "source", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "tags", Type: arrow.ListOf(KeyValueobjectStruct), Nullable: true},
	{Name: "tenant_uid", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "transformation_info_list", Type: arrow.ListOf(TransformationInfoStruct), Nullable: true},
	{Name: "transmit_time", Type: arrow.FixedWidthTypes.Timestamp_ms, Nullable: true},
	{Name: "type", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "uid", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "untruncated_size", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "version", Type: arrow.BinaryTypes.String, Nullable: false},
}

var MetadataStruct = arrow.StructOf(MetadataFields...)

var MetadataSchema = arrow.NewSchema(MetadataFields, nil)
var MetadataClassname = "metadata"
