// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type Metric struct {

	// Name: The name of the metric.
	Name string `json:"name" parquet:"name"`

	// Value: The value of the metric.
	Value string `json:"value" parquet:"value"`
}

func (v *Metric) Observable() (*int, string) {
	return nil, ""
}

var MetricFields = []arrow.Field{
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: false},
	{Name: "value", Type: arrow.BinaryTypes.String, Nullable: false},
}

var MetricStruct = arrow.StructOf(MetricFields...)

var MetricSchema = arrow.NewSchema(MetricFields, nil)
var MetricClassname = "metric"
