// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type Module struct {

	// Base Address: The memory address where the module was loaded.
	BaseAddress *string `json:"base_address,omitempty" parquet:"base_address,optional"`

	// File: The module file object.
	File *File `json:"file,omitempty" parquet:"file,optional"`

	// Function Invocation: Details about the invocation of the function given in <code>function_name</code>.
	FunctionInvocation *FunctionInvocation `json:"function_invocation,omitempty" parquet:"function_invocation,optional"`

	// Function Name: The invoked function in the module. For load and unload events, this is the entry-point function of the module. The system calls the entry-point function whenever a process or thread loads or unloads the module.
	FunctionName *string `json:"function_name,omitempty" parquet:"function_name,optional"`

	// Load Type: The load type, normalized to the caption of the load_type_id value. In the case of 'Other', it is defined by the event source.
	LoadType *string `json:"load_type,omitempty" parquet:"load_type,optional"`

	// Load Type ID: The normalized identifier for how the module was loaded in memory.
	LoadTypeId *int32 `json:"load_type_id,omitempty" parquet:"load_type_id,optional"`

	// Start Address: The start address of the execution.
	StartAddress *string `json:"start_address,omitempty" parquet:"start_address,optional"`

	// Type: The module type.
	Type *string `json:"type,omitempty" parquet:"type,optional"`
}

func (v *Module) Observable() (*int, string) {
	return nil, ""
}

var ModuleFields = []arrow.Field{
	{Name: "base_address", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "file", Type: FileStruct, Nullable: true},
	{Name: "function_invocation", Type: FunctionInvocationStruct, Nullable: true},
	{Name: "function_name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "load_type", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "load_type_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "start_address", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "type", Type: arrow.BinaryTypes.String, Nullable: true},
}

var ModuleStruct = arrow.StructOf(ModuleFields...)

var ModuleSchema = arrow.NewSchema(ModuleFields, nil)
var ModuleClassname = "module"
