// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type NetworkEndpoint struct {

	// Agent List: A list of <code>agent</code> objects associated with a device, endpoint, or resource.
	AgentList []Agent `json:"agent_list,omitempty" parquet:"agent_list,list,optional"`

	// Autonomous System: The Autonomous System details associated with an IP address.
	AutonomousSystem *AutonomousSystem `json:"autonomous_system,omitempty" parquet:"autonomous_system,optional"`

	// Container: The information describing an instance of a container. A container is a prepackaged, portable system image that runs isolated on an existing system using a container runtime like containerd.
	Container *Container `json:"container,omitempty" parquet:"container,optional"`

	// Domain: The name of the domain that the endpoint belongs to or that corresponds to the endpoint.
	Domain *string `json:"domain,omitempty" parquet:"domain,optional"`

	// Hostname: The fully qualified name of the endpoint.
	Hostname *string `json:"hostname,omitempty" parquet:"hostname,optional"`

	// Hardware Info: The endpoint hardware information.
	HwInfo *DeviceHardwareInfo `json:"hw_info,omitempty" parquet:"hw_info,optional"`

	// Instance ID: The unique identifier of a VM instance.
	InstanceUid *string `json:"instance_uid,omitempty" parquet:"instance_uid,optional"`

	// Network Interface Name: The name of the network interface (e.g. eth2).
	InterfaceName *string `json:"interface_name,omitempty" parquet:"interface_name,optional"`

	// Network Interface ID: The unique identifier of the network interface.
	InterfaceUid *string `json:"interface_uid,omitempty" parquet:"interface_uid,optional"`

	// Intermediate IP Addresses: The intermediate IP Addresses. For example, the IP addresses in the HTTP X-Forwarded-For header.
	IntermediateIps []string `json:"intermediate_ips,omitempty" parquet:"intermediate_ips,list,optional"`

	// IP Address: The IP address of the endpoint, in either IPv4 or IPv6 format.
	Ip *string `json:"ip,omitempty" parquet:"ip,optional"`

	// ISP Name: The name of the Internet Service Provider (ISP).
	Isp *string `json:"isp,omitempty" parquet:"isp,optional"`

	// ISP Org: The organization name of the Internet Service Provider (ISP). This represents the parent organization or company that owns/operates the ISP. For example, Comcast Corporation would be the ISP org for Xfinity internet service. This attribute helps identify the ultimate provider when ISPs operate under different brand names.
	IspOrg *string `json:"isp_org,omitempty" parquet:"isp_org,optional"`

	// Geo Location: The geographical location of the endpoint.
	Location *GeoLocation `json:"location,omitempty" parquet:"location,optional"`

	// MAC Address: The Media Access Control (MAC) address of the endpoint.
	Mac *string `json:"mac,omitempty" parquet:"mac,optional"`

	// Name: The short name of the endpoint.
	Name *string `json:"name,omitempty" parquet:"name,optional"`

	// Namespace PID: If running under a process namespace (such as in a container), the process identifier within that process namespace.
	NamespacePid *int32 `json:"namespace_pid,omitempty" parquet:"namespace_pid,optional"`

	// Network Scope: Indicates whether the endpoint resides inside the customer’s network, outside on the Internet, or if its location relative to the customer’s network cannot be determined. The value is normalized to the caption of the <code>network_scope_id</code>.
	NetworkScope *string `json:"network_scope,omitempty" parquet:"network_scope,optional"`

	// Network Scope ID: The normalized identifier of the endpoint’s network scope. The normalized network scope identifier indicates whether the endpoint resides inside the customer’s network, outside on the Internet, or if its location relative to the customer’s network cannot be determined.
	NetworkScopeId *int32 `json:"network_scope_id,omitempty" parquet:"network_scope_id,optional"`

	// OS: The endpoint operating system.
	Os *OperatingSystemOS `json:"os,omitempty" parquet:"os,optional"`

	// Owner: The identity of the service or user account that owns the endpoint or was last logged into it.
	Owner *User `json:"owner,omitempty" parquet:"owner,optional"`

	// Port: The port used for communication within the network connection.
	Port *int32 `json:"port,omitempty" parquet:"port,optional"`

	// Proxy Endpoint: The network proxy information pertaining to a specific endpoint. This can be used to describe information pertaining to network address translation (NAT).
	ProxyEndpoint *NetworkProxyEndpoint `json:"proxy_endpoint,omitempty" parquet:"proxy_endpoint,optional"`

	// Subnet UID: The unique identifier of a virtual subnet.
	SubnetUid *string `json:"subnet_uid,omitempty" parquet:"subnet_uid,optional"`

	// Service Name: The service name in service-to-service connections. For example, AWS VPC logs the pkt-src-aws-service and pkt-dst-aws-service fields identify the connection is coming from or going to an AWS service.
	SvcName *string `json:"svc_name,omitempty" parquet:"svc_name,optional"`

	// Type: The network endpoint type. For example: <code>unknown</code>, <code>server</code>, <code>desktop</code>, <code>laptop</code>, <code>tablet</code>, <code>mobile</code>, <code>virtual</code>, <code>browser</code>, or <code>other</code>.
	Type *string `json:"type,omitempty" parquet:"type,optional"`

	// Type ID: The network endpoint type ID.
	TypeId *int32 `json:"type_id,omitempty" parquet:"type_id,optional"`

	// Unique ID: The unique identifier of the endpoint.
	Uid *string `json:"uid,omitempty" parquet:"uid,optional"`

	// VLAN: The Virtual LAN identifier.
	VlanUid *string `json:"vlan_uid,omitempty" parquet:"vlan_uid,optional"`

	// VPC UID: The unique identifier of the Virtual Private Cloud (VPC).
	VpcUid *string `json:"vpc_uid,omitempty" parquet:"vpc_uid,optional"`

	// Network Zone: The network zone or LAN segment.
	Zone *string `json:"zone,omitempty" parquet:"zone,optional"`
}

func (v *NetworkEndpoint) Observable() (*int, string) {
	typeId := 20
	return &typeId, "network_endpoint"
}

var NetworkEndpointFields = []arrow.Field{
	{Name: "agent_list", Type: arrow.ListOf(AgentStruct), Nullable: true},
	{Name: "autonomous_system", Type: AutonomousSystemStruct, Nullable: true},
	{Name: "container", Type: ContainerStruct, Nullable: true},
	{Name: "domain", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "hostname", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "hw_info", Type: DeviceHardwareInfoStruct, Nullable: true},
	{Name: "instance_uid", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "interface_name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "interface_uid", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "intermediate_ips", Type: arrow.ListOf(arrow.BinaryTypes.String), Nullable: true},
	{Name: "ip", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "isp", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "isp_org", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "location", Type: GeoLocationStruct, Nullable: true},
	{Name: "mac", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "namespace_pid", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "network_scope", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "network_scope_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "os", Type: OperatingSystemOSStruct, Nullable: true},
	{Name: "owner", Type: UserStruct, Nullable: true},
	{Name: "port", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "proxy_endpoint", Type: NetworkProxyEndpointStruct, Nullable: true},
	{Name: "subnet_uid", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "svc_name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "type", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "type_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "uid", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "vlan_uid", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "vpc_uid", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "zone", Type: arrow.BinaryTypes.String, Nullable: true},
}

var NetworkEndpointStruct = arrow.StructOf(NetworkEndpointFields...)

var NetworkEndpointSchema = arrow.NewSchema(NetworkEndpointFields, nil)
var NetworkEndpointClassname = "network_endpoint"
