// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type SoftwarePackage struct {

	// Architecture: Architecture is a shorthand name describing the type of computer hardware the packaged software is meant to run on.
	Architecture *string `json:"architecture,omitempty" parquet:"architecture,optional"`

	// The product CPE identifier: The Common Platform Enumeration (CPE) name as described by (<a target='_blank' href='https://nvd.nist.gov/products/cpe'>NIST</a>) For example: <code>cpe:/a:apple:safari:16.2</code>.
	CpeName *string `json:"cpe_name,omitempty" parquet:"cpe_name,optional"`

	// Epoch: The software package epoch. Epoch is a way to define weighted dependencies based on version numbers.
	Epoch *int32 `json:"epoch,omitempty" parquet:"epoch,optional"`

	// Hash: Cryptographic hash to identify the binary instance of a software component. This can include any component such file, package, or library.
	Hash *Fingerprint `json:"hash,omitempty" parquet:"hash,optional"`

	// Software License: The software license applied to this package.
	License *string `json:"license,omitempty" parquet:"license,optional"`

	// Software License URL: The URL pointing to the license applied on package or software. This is typically a <code>LICENSE.md</code> file within a repository.
	LicenseUrl *string `json:"license_url,omitempty" parquet:"license_url,optional"`

	// Name: The software package name.
	Name string `json:"name" parquet:"name"`

	// Package Manager: The software packager manager utilized to manage a package on a system, e.g. npm, yum, dpkg etc.
	PackageManager *string `json:"package_manager,omitempty" parquet:"package_manager,optional"`

	// Package Manager URL: The URL of the package or library at the package manager, or the specific URL or URI of an internal package manager link such as <code>AWS CodeArtifact</code> or <code>Artifactory</code>.
	PackageManagerUrl *string `json:"package_manager_url,omitempty" parquet:"package_manager_url,optional"`

	// Package URL: A purl is a URL string used to identify and locate a software package in a mostly universal and uniform way across programming languages, package managers, packaging conventions, tools, APIs and databases.
	Purl *string `json:"purl,omitempty" parquet:"purl,optional"`

	// Software Release Details: Release is the number of times a version of the software has been packaged.
	Release *string `json:"release,omitempty" parquet:"release,optional"`

	// Source URL: The link to the specific library or package such as within <code>GitHub</code>, this is different from the link to the package manager where the library or package is hosted.
	SrcUrl *string `json:"src_url,omitempty" parquet:"src_url,optional"`

	// Type: The type of software package, normalized to the caption of the <code>type_id</code> value. In the case of 'Other', it is defined by the source.
	Type *string `json:"type,omitempty" parquet:"type,optional"`

	// Type ID: The type of software package.
	TypeId *int32 `json:"type_id,omitempty" parquet:"type_id,optional"`

	// Package UID: A unique identifier for the package or library reported by the source tool. E.g., the <code>libId</code> within the <code>sbom</code> field of an OX Security Issue or the SPDX <code>components.*.bom-ref</code>.
	Uid *string `json:"uid,omitempty" parquet:"uid,optional"`

	// Vendor Name: The name of the vendor who published the software package.
	VendorName *string `json:"vendor_name,omitempty" parquet:"vendor_name,optional"`

	// Version: The software package version.
	Version string `json:"version" parquet:"version"`
}

func (v *SoftwarePackage) Observable() (*int, string) {
	return nil, ""
}

var SoftwarePackageFields = []arrow.Field{
	{Name: "architecture", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "cpe_name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "epoch", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "hash", Type: FingerprintStruct, Nullable: true},
	{Name: "license", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "license_url", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: false},
	{Name: "package_manager", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "package_manager_url", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "purl", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "release", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "src_url", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "type", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "type_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "uid", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "vendor_name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "version", Type: arrow.BinaryTypes.String, Nullable: false},
}

var SoftwarePackageStruct = arrow.StructOf(SoftwarePackageFields...)

var SoftwarePackageSchema = arrow.NewSchema(SoftwarePackageFields, nil)
var SoftwarePackageClassname = "package"
