// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type Parameter struct {

	// Name: The parameter name.
	Name *string `json:"name,omitempty" parquet:"name,optional"`

	// Post-Value: The parameter value after function execution.
	PostValue *string `json:"post_value,omitempty" parquet:"post_value,optional"`

	// Pre-Value: The parameter value before function execution.
	PreValue *string `json:"pre_value,omitempty" parquet:"pre_value,optional"`
}

func (v *Parameter) Observable() (*int, string) {
	return nil, ""
}

var ParameterFields = []arrow.Field{
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "post_value", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "pre_value", Type: arrow.BinaryTypes.String, Nullable: true},
}

var ParameterStruct = arrow.StructOf(ParameterFields...)

var ParameterSchema = arrow.NewSchema(ParameterFields, nil)
var ParameterClassname = "parameter"
