// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type PeripheralDevice struct {

	// Class: The class of the peripheral device.
	Class *string `json:"class,omitempty" parquet:"class,optional"`

	// Model: The peripheral device model.
	Model *string `json:"model,omitempty" parquet:"model,optional"`

	// Name: The name of the peripheral device.
	Name string `json:"name" parquet:"name"`

	// Serial Number: The peripheral device serial number.
	SerialNumber *string `json:"serial_number,omitempty" parquet:"serial_number,optional"`

	// Peripheral Device Type: The Peripheral Device type, normalized to the caption of the <code>type_id</code> value. In the case of 'Other', it is defined by the source.
	Type *string `json:"type,omitempty" parquet:"type,optional"`

	// Peripheral Device Type ID: The normalized peripheral device type ID.
	TypeId *int32 `json:"type_id,omitempty" parquet:"type_id,optional"`

	// Unique ID: The unique identifier of the peripheral device.
	Uid *string `json:"uid,omitempty" parquet:"uid,optional"`

	// Vendor ID List: The list of vendor IDs for the peripheral device.
	VendorIdList []string `json:"vendor_id_list,omitempty" parquet:"vendor_id_list,list,optional"`

	// Vendor Name: The primary vendor name for the peripheral device.
	VendorName *string `json:"vendor_name,omitempty" parquet:"vendor_name,optional"`
}

func (v *PeripheralDevice) Observable() (*int, string) {
	return nil, ""
}

var PeripheralDeviceFields = []arrow.Field{
	{Name: "class", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "model", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: false},
	{Name: "serial_number", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "type", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "type_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "uid", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "vendor_id_list", Type: arrow.ListOf(arrow.BinaryTypes.String), Nullable: true},
	{Name: "vendor_name", Type: arrow.BinaryTypes.String, Nullable: true},
}

var PeripheralDeviceStruct = arrow.StructOf(PeripheralDeviceFields...)

var PeripheralDeviceSchema = arrow.NewSchema(PeripheralDeviceFields, nil)
var PeripheralDeviceClassname = "peripheral_device"
