// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type PortInformation struct {

	// Port: The port number. For example: <code>80</code>, <code>443</code>, <code>22</code>.
	Port int32 `json:"port" parquet:"port"`

	// Protocol Name: The IP protocol name in lowercase, as defined by the Internet Assigned Numbers Authority (IANA). For example: <code>tcp</code> or <code>udp</code>.
	ProtocolName *string `json:"protocol_name,omitempty" parquet:"protocol_name,optional"`

	// Protocol Number: The IP protocol number, as defined by the Internet Assigned Numbers Authority (IANA). For example: <code>6</code> for TCP and <code>17</code> for UDP.
	ProtocolNum *int32 `json:"protocol_num,omitempty" parquet:"protocol_num,optional"`
}

func (v *PortInformation) Observable() (*int, string) {
	return nil, ""
}

var PortInformationFields = []arrow.Field{
	{Name: "port", Type: arrow.PrimitiveTypes.Int32, Nullable: false},
	{Name: "protocol_name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "protocol_num", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
}

var PortInformationStruct = arrow.StructOf(PortInformationFields...)

var PortInformationSchema = arrow.NewSchema(PortInformationFields, nil)
var PortInformationClassname = "port_info"
