// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type ProcessEntity struct {

	// Command Line: The full command line used to launch an application, service, process, or job. For example: <code>ssh user@10.0.0.10</code>. If the command line is unavailable or missing, the empty string <code>”</code> is to be used.
	CmdLine *string `json:"cmd_line,omitempty" parquet:"cmd_line,optional"`

	// Common Process Identifier: A unique process identifier that can be assigned deterministically by multiple system data producers.
	Cpid *string `json:"cpid,omitempty" parquet:"cpid,optional"`

	// Created Time: The time when the process was created/started.
	CreatedTime int64 `json:"created_time,omitempty" parquet:"created_time,timestamp_millis,timestamp(millisecond),optional"`

	// Name: The friendly name of the process, for example: <code>Notepad++</code>.
	Name *string `json:"name,omitempty" parquet:"name,optional"`

	// Path: The process file path.
	Path *string `json:"path,omitempty" parquet:"path,optional"`

	// Process ID: The process identifier, as reported by the operating system. Process ID (PID) is a number used by the operating system to uniquely identify an active process.
	Pid *int32 `json:"pid,omitempty" parquet:"pid,optional"`

	// Unique ID: A unique identifier for this process assigned by the producer (tool).  Facilitates correlation of a process event with other events for that process.
	Uid *string `json:"uid,omitempty" parquet:"uid,optional"`
}

func (v *ProcessEntity) Observable() (*int, string) {
	return nil, ""
}

var ProcessEntityFields = []arrow.Field{
	{Name: "cmd_line", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "cpid", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "created_time", Type: arrow.FixedWidthTypes.Timestamp_ms, Nullable: true},
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "path", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "pid", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "uid", Type: arrow.BinaryTypes.String, Nullable: true},
}

var ProcessEntityStruct = arrow.StructOf(ProcessEntityFields...)

var ProcessEntitySchema = arrow.NewSchema(ProcessEntityFields, nil)
var ProcessEntityClassname = "process_entity"
