// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type ProgrammaticCredential struct {

	// Last Used Time: The timestamp when this programmatic credential was last used for authentication or API access. This helps track credential usage patterns, identify dormant credentials that may pose security risks, and support credential lifecycle management. The timestamp should reflect the most recent successful authentication or API call using this credential.
	LastUsedTime int64 `json:"last_used_time,omitempty" parquet:"last_used_time,timestamp_millis,timestamp(millisecond),optional"`

	// Type: The type or category of programmatic credential, normalized to the caption of the type_id value. In the case of 'Other', it is defined by the event source. Examples include 'API Key', 'Service Account Key', 'Access Token', 'Client Certificate', 'OAuth Token', 'Personal Access Token', etc.
	Type *string `json:"type,omitempty" parquet:"type,optional"`

	// Unique ID: The unique identifier of the programmatic credential. This could be an API key ID, service account key ID, access token identifier, certificate serial number, or other unique identifier that distinguishes this credential from others. Examples: AWS Access Key ID, GCP Service Account Key ID, Azure Application ID, or OAuth2 token identifier.
	Uid string `json:"uid" parquet:"uid"`
}

func (v *ProgrammaticCredential) Observable() (*int, string) {
	return nil, ""
}

var ProgrammaticCredentialFields = []arrow.Field{
	{Name: "last_used_time", Type: arrow.FixedWidthTypes.Timestamp_ms, Nullable: true},
	{Name: "type", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "uid", Type: arrow.BinaryTypes.String, Nullable: false},
}

var ProgrammaticCredentialStruct = arrow.StructOf(ProgrammaticCredentialFields...)

var ProgrammaticCredentialSchema = arrow.NewSchema(ProgrammaticCredentialFields, nil)
var ProgrammaticCredentialClassname = "programmatic_credential"
