// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type QueryInformation struct {

	// Total Bytes: The size of the data returned from the query.
	Bytes *int64 `json:"bytes,omitempty" parquet:"bytes,optional"`

	// Data: The data returned from the query execution.
	Data *string `json:"data,omitempty" parquet:"data,optional"`

	// Name: The query name for a saved or scheduled query.
	Name *string `json:"name,omitempty" parquet:"name,optional"`

	// Query String: A string representing the query code being run. For example: <code>SELECT * FROM my_table</code>
	QueryString string `json:"query_string" parquet:"query_string"`

	// Query Time: The time when the query was run.
	QueryTime int64 `json:"query_time,omitempty" parquet:"query_time,timestamp_millis,timestamp(millisecond),optional"`

	// Unique ID: The unique identifier of the query.
	Uid *string `json:"uid,omitempty" parquet:"uid,optional"`
}

func (v *QueryInformation) Observable() (*int, string) {
	return nil, ""
}

var QueryInformationFields = []arrow.Field{
	{Name: "bytes", Type: arrow.PrimitiveTypes.Int64, Nullable: true},
	{Name: "data", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "query_string", Type: arrow.BinaryTypes.String, Nullable: false},
	{Name: "query_time", Type: arrow.FixedWidthTypes.Timestamp_ms, Nullable: true},
	{Name: "uid", Type: arrow.BinaryTypes.String, Nullable: true},
}

var QueryInformationStruct = arrow.StructOf(QueryInformationFields...)

var QueryInformationSchema = arrow.NewSchema(QueryInformationFields, nil)
var QueryInformationClassname = "query_info"
