// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type Reputation struct {

	// Reputation Score: The reputation score as reported by the event source.
	BaseScore float64 `json:"base_score" parquet:"base_score"`

	// Provider: The provider of the reputation information.
	Provider *string `json:"provider,omitempty" parquet:"provider,optional"`

	// Reputation Score: The reputation score, normalized to the caption of the score_id value. In the case of 'Other', it is defined by the event source.
	Score *string `json:"score,omitempty" parquet:"score,optional"`

	// Reputation Score ID: The normalized reputation score identifier.
	ScoreId int32 `json:"score_id" parquet:"score_id"`
}

func (v *Reputation) Observable() (*int, string) {
	return nil, ""
}

var ReputationFields = []arrow.Field{
	{Name: "base_score", Type: arrow.PrimitiveTypes.Float64, Nullable: false},
	{Name: "provider", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "score", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "score_id", Type: arrow.PrimitiveTypes.Int32, Nullable: false},
}

var ReputationStruct = arrow.StructOf(ReputationFields...)

var ReputationSchema = arrow.NewSchema(ReputationFields, nil)
var ReputationClassname = "reputation"
