// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type RequestElements struct {

	// Containers: When working with containerized applications, the set of containers which write to the standard the output of a particular logging driver. For example, this may be the set of containers involved in handling api requests and responses for a containerized application.
	Containers []Container `json:"containers,omitempty" parquet:"containers,list,optional"`

	// Data: The additional data that is associated with the api request.
	Data *string `json:"data,omitempty" parquet:"data,optional"`

	// Flags: The communication flags that are associated with the api request.
	Flags []string `json:"flags,omitempty" parquet:"flags,list,optional"`

	// Unique ID: The unique request identifier.
	Uid string `json:"uid" parquet:"uid"`
}

func (v *RequestElements) Observable() (*int, string) {
	return nil, ""
}

var RequestElementsFields = []arrow.Field{
	{Name: "containers", Type: arrow.ListOf(ContainerStruct), Nullable: true},
	{Name: "data", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "flags", Type: arrow.ListOf(arrow.BinaryTypes.String), Nullable: true},
	{Name: "uid", Type: arrow.BinaryTypes.String, Nullable: false},
}

var RequestElementsStruct = arrow.StructOf(RequestElementsFields...)

var RequestElementsSchema = arrow.NewSchema(RequestElementsFields, nil)
var RequestElementsClassname = "request"
