// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type ResponseElements struct {

	// Response Code: The numeric response sent to a request.
	Code *int32 `json:"code,omitempty" parquet:"code,optional"`

	// Containers: When working with containerized applications, the set of containers which write to the standard the output of a particular logging driver. For example, this may be the set of containers involved in handling api requests and responses for a containerized application.
	Containers []Container `json:"containers,omitempty" parquet:"containers,list,optional"`

	// Data: The additional data that is associated with the api response.
	Data *string `json:"data,omitempty" parquet:"data,optional"`

	// Error Code: Error Code
	Error *string `json:"error,omitempty" parquet:"error,optional"`

	// Error Message: Error Message
	ErrorMessage *string `json:"error_message,omitempty" parquet:"error_message,optional"`

	// Flags: The communication flags that are associated with the api response.
	Flags []string `json:"flags,omitempty" parquet:"flags,list,optional"`

	// Message: The description of the event/finding, as defined by the source.
	Message *string `json:"message,omitempty" parquet:"message,optional"`
}

func (v *ResponseElements) Observable() (*int, string) {
	return nil, ""
}

var ResponseElementsFields = []arrow.Field{
	{Name: "code", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "containers", Type: arrow.ListOf(ContainerStruct), Nullable: true},
	{Name: "data", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "error", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "error_message", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "flags", Type: arrow.ListOf(arrow.BinaryTypes.String), Nullable: true},
	{Name: "message", Type: arrow.BinaryTypes.String, Nullable: true},
}

var ResponseElementsStruct = arrow.StructOf(ResponseElementsFields...)

var ResponseElementsSchema = arrow.NewSchema(ResponseElementsFields, nil)
var ResponseElementsClassname = "response"
