// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type Rule struct {

	// Category: The rule category.
	Category *string `json:"category,omitempty" parquet:"category,optional"`

	// Description: The description of the rule that generated the event.
	Desc *string `json:"desc,omitempty" parquet:"desc,optional"`

	// Name: The name of the rule that generated the event.
	Name *string `json:"name,omitempty" parquet:"name,optional"`

	// Type: The rule type.
	Type *string `json:"type,omitempty" parquet:"type,optional"`

	// Unique ID: The unique identifier of the rule that generated the event.
	Uid *string `json:"uid,omitempty" parquet:"uid,optional"`

	// Version: The rule version. For example: <code>1.1</code>.
	Version *string `json:"version,omitempty" parquet:"version,optional"`
}

func (v *Rule) Observable() (*int, string) {
	return nil, ""
}

var RuleFields = []arrow.Field{
	{Name: "category", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "desc", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "type", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "uid", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "version", Type: arrow.BinaryTypes.String, Nullable: true},
}

var RuleStruct = arrow.StructOf(RuleFields...)

var RuleSchema = arrow.NewSchema(RuleFields, nil)
var RuleClassname = "rule"
