// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type SubjectAlternativeName struct {

	// Name: Name of SAN (e.g. The actual IP Address or domain.)
	Name string `json:"name" parquet:"name"`

	// Type: Type descriptor of SAN (e.g. IP Address/domain/etc.)
	Type string `json:"type" parquet:"type"`
}

func (v *SubjectAlternativeName) Observable() (*int, string) {
	return nil, ""
}

var SubjectAlternativeNameFields = []arrow.Field{
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: false},
	{Name: "type", Type: arrow.BinaryTypes.String, Nullable: false},
}

var SubjectAlternativeNameStruct = arrow.StructOf(SubjectAlternativeNameFields...)

var SubjectAlternativeNameSchema = arrow.NewSchema(SubjectAlternativeNameFields, nil)
var SubjectAlternativeNameClassname = "san"
