// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type Scan struct {

	// Name: The administrator-supplied or application-generated name of the scan. For example: "Home office weekly user database scan", "Scan folders for viruses", "Full system virus scan"
	Name *string `json:"name,omitempty" parquet:"name,optional"`

	// Type: The type of scan.
	Type *string `json:"type,omitempty" parquet:"type,optional"`

	// Type ID: The type id of the scan.
	TypeId int32 `json:"type_id" parquet:"type_id"`

	// Scan UID: The application-defined unique identifier assigned to an instance of a scan.
	Uid *string `json:"uid,omitempty" parquet:"uid,optional"`
}

func (v *Scan) Observable() (*int, string) {
	return nil, ""
}

var ScanFields = []arrow.Field{
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "type", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "type_id", Type: arrow.PrimitiveTypes.Int32, Nullable: false},
	{Name: "uid", Type: arrow.BinaryTypes.String, Nullable: true},
}

var ScanStruct = arrow.StructOf(ScanFields...)

var ScanSchema = arrow.NewSchema(ScanFields, nil)
var ScanClassname = "scan"
