// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type SecurityState struct {

	// Security State: The security state, normalized to the caption of the state_id value. In the case of 'Other', it is defined by the source.
	State *string `json:"state,omitempty" parquet:"state,optional"`

	// Security State ID: The security state of the managed entity.
	StateId *int32 `json:"state_id,omitempty" parquet:"state_id,optional"`
}

func (v *SecurityState) Observable() (*int, string) {
	return nil, ""
}

var SecurityStateFields = []arrow.Field{
	{Name: "state", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "state_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
}

var SecurityStateStruct = arrow.StructOf(SecurityStateFields...)

var SecurityStateSchema = arrow.NewSchema(SecurityStateFields, nil)
var SecurityStateClassname = "security_state"
