// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type Service struct {

	// Labels: The list of labels associated with the service.
	Labels []string `json:"labels,omitempty" parquet:"labels,list,optional"`

	// Name: The name of the service.
	Name *string `json:"name,omitempty" parquet:"name,optional"`

	// Tags: The list of tags; <code>{key:value}</code> pairs associated to the service.
	Tags []KeyValueobject `json:"tags,omitempty" parquet:"tags,list,optional"`

	// Unique ID: The unique identifier of the service.
	Uid *string `json:"uid,omitempty" parquet:"uid,optional"`

	// Version: The version of the service.
	Version *string `json:"version,omitempty" parquet:"version,optional"`
}

func (v *Service) Observable() (*int, string) {
	return nil, ""
}

var ServiceFields = []arrow.Field{
	{Name: "labels", Type: arrow.ListOf(arrow.BinaryTypes.String), Nullable: true},
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "tags", Type: arrow.ListOf(KeyValueobjectStruct), Nullable: true},
	{Name: "uid", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "version", Type: arrow.BinaryTypes.String, Nullable: true},
}

var ServiceStruct = arrow.StructOf(ServiceFields...)

var ServiceSchema = arrow.NewSchema(ServiceFields, nil)
var ServiceClassname = "service"
