// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type Table struct {

	// Created Time: The time when the table was known to have been created.
	CreatedTime int64 `json:"created_time,omitempty" parquet:"created_time,timestamp_millis,timestamp(millisecond),optional"`

	// Description: The description of the table.
	Desc *string `json:"desc,omitempty" parquet:"desc,optional"`

	// Groups: The group names to which the table belongs.
	Groups []Group `json:"groups,omitempty" parquet:"groups,list,optional"`

	// Modified Time: The most recent time when any changes, updates, or modifications were made within the table.
	ModifiedTime int64 `json:"modified_time,omitempty" parquet:"modified_time,timestamp_millis,timestamp(millisecond),optional"`

	// Name: The table name, ordinarily as assigned by a database administrator.
	Name *string `json:"name,omitempty" parquet:"name,optional"`

	// Size: The size of the data table in bytes.
	Size *int64 `json:"size,omitempty" parquet:"size,optional"`

	// Unique ID: The unique identifier of the table.
	Uid *string `json:"uid,omitempty" parquet:"uid,optional"`
}

func (v *Table) Observable() (*int, string) {
	return nil, ""
}

var TableFields = []arrow.Field{
	{Name: "created_time", Type: arrow.FixedWidthTypes.Timestamp_ms, Nullable: true},
	{Name: "desc", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "groups", Type: arrow.ListOf(GroupStruct), Nullable: true},
	{Name: "modified_time", Type: arrow.FixedWidthTypes.Timestamp_ms, Nullable: true},
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "size", Type: arrow.PrimitiveTypes.Int64, Nullable: true},
	{Name: "uid", Type: arrow.BinaryTypes.String, Nullable: true},
}

var TableStruct = arrow.StructOf(TableFields...)

var TableSchema = arrow.NewSchema(TableFields, nil)
var TableClassname = "table"
