// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type MITRETactic struct {

	// Name: The Tactic name that is associated with the attack technique. For example: <code>Reconnaissance</code> or <code>ML Model Access</code>.
	Name *string `json:"name,omitempty" parquet:"name,optional"`

	// Source URL: The versioned permalink of the Tactic. For example: <code>https://attack.mitre.org/versions/v14/tactics/TA0043/</code>.
	SrcUrl *string `json:"src_url,omitempty" parquet:"src_url,optional"`

	// Unique ID: The Tactic ID that is associated with the attack technique. For example: <code>TA0043</code>, or <code>AML.TA0000</code>.
	Uid *string `json:"uid,omitempty" parquet:"uid,optional"`
}

func (v *MITRETactic) Observable() (*int, string) {
	return nil, ""
}

var MITRETacticFields = []arrow.Field{
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "src_url", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "uid", Type: arrow.BinaryTypes.String, Nullable: true},
}

var MITRETacticStruct = arrow.StructOf(MITRETacticFields...)

var MITRETacticSchema = arrow.NewSchema(MITRETacticFields, nil)
var MITRETacticClassname = "tactic"
