// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type MITRETechnique struct {

	// Name: The name of the attack technique. For example: <code>Active Scanning</code> or <code>AI Model Inference API Access</code>.
	Name *string `json:"name,omitempty" parquet:"name,optional"`

	// Source URL: The versioned permalink of the attack technique. For example: <code>https://attack.mitre.org/versions/v14/techniques/T1595/</code>.
	SrcUrl *string `json:"src_url,omitempty" parquet:"src_url,optional"`

	// Unique ID: The unique identifier of the attack technique. For example: <code>T1595</code> or <code>AML.T0040</code>.
	Uid *string `json:"uid,omitempty" parquet:"uid,optional"`
}

func (v *MITRETechnique) Observable() (*int, string) {
	return nil, ""
}

var MITRETechniqueFields = []arrow.Field{
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "src_url", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "uid", Type: arrow.BinaryTypes.String, Nullable: true},
}

var MITRETechniqueStruct = arrow.StructOf(MITRETechniqueFields...)

var MITRETechniqueSchema = arrow.NewSchema(MITRETechniqueFields, nil)
var MITRETechniqueClassname = "technique"
