// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type ThreatActor struct {

	// Name: The name of the threat actor.
	Name string `json:"name" parquet:"name"`

	// Threat Actor Type: The classification of the threat actor based on their motivations, capabilities, or affiliations. Common types include nation-state actors, cybercriminal groups, hacktivists, or insider threats.
	Type *string `json:"type,omitempty" parquet:"type,optional"`

	// Threat Actor Type ID: The normalized datastore resource type identifier.
	TypeId *int32 `json:"type_id,omitempty" parquet:"type_id,optional"`
}

func (v *ThreatActor) Observable() (*int, string) {
	return nil, ""
}

var ThreatActorFields = []arrow.Field{
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: false},
	{Name: "type", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "type_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
}

var ThreatActorStruct = arrow.StructOf(ThreatActorFields...)

var ThreatActorSchema = arrow.NewSchema(ThreatActorFields, nil)
var ThreatActorClassname = "threat_actor"
