// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type TLSExtension struct {

	// Data: The data contains information specific to the particular extension type.
	Data *string `json:"data,omitempty" parquet:"data,optional"`

	// Type: The TLS extension type. For example: <code>Server Name</code>.
	Type *string `json:"type,omitempty" parquet:"type,optional"`

	// Type ID: The TLS extension type identifier. See <a target='_blank' href='https://datatracker.ietf.org/doc/html/rfc8446#page-35'>The Transport Layer Security (TLS) extension page</a>.
	TypeId int32 `json:"type_id" parquet:"type_id"`
}

func (v *TLSExtension) Observable() (*int, string) {
	return nil, ""
}

var TLSExtensionFields = []arrow.Field{
	{Name: "data", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "type", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "type_id", Type: arrow.PrimitiveTypes.Int32, Nullable: false},
}

var TLSExtensionStruct = arrow.StructOf(TLSExtensionFields...)

var TLSExtensionSchema = arrow.NewSchema(TLSExtensionFields, nil)
var TLSExtensionClassname = "tls_extension"
