// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type VendorAttributes struct {

	// Severity: The finding severity, as reported by the Vendor (Finding Provider). The value should be normalized to the caption of the <code>severity_id</code> value. In the case of 'Other', it is defined by the source.
	Severity *string `json:"severity,omitempty" parquet:"severity,optional"`

	// Severity ID: The finding severity ID, as reported by the Vendor (Finding Provider).
	SeverityId *int32 `json:"severity_id,omitempty" parquet:"severity_id,optional"`
}

func (v *VendorAttributes) Observable() (*int, string) {
	return nil, ""
}

var VendorAttributesFields = []arrow.Field{
	{Name: "severity", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "severity_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
}

var VendorAttributesStruct = arrow.StructOf(VendorAttributesFields...)

var VendorAttributesSchema = arrow.NewSchema(VendorAttributesFields, nil)
var VendorAttributesClassname = "vendor_attributes"
