// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_7_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type WindowsResource struct {

	// Created Time: The time when the resource was created.
	CreatedTime int64 `json:"created_time,omitempty" parquet:"created_time,timestamp_millis,timestamp(millisecond),optional"`

	// Data: Additional data describing the resource.
	Data *string `json:"data,omitempty" parquet:"data,optional"`

	// Data Classification: A list of Data Classification objects, that include information about data classification levels and data category types, identified by a classifier.
	DataClassifications []DataClassification `json:"data_classifications,omitempty" parquet:"data_classifications,list,optional"`

	// Details: The string detailing the attributes of the resource object.
	Details *string `json:"details,omitempty" parquet:"details,optional"`

	// Labels: The list of labels associated to the resource.
	Labels []string `json:"labels,omitempty" parquet:"labels,list,optional"`

	// Modified Time: The time when the resource was last modified.
	ModifiedTime int64 `json:"modified_time,omitempty" parquet:"modified_time,timestamp_millis,timestamp(millisecond),optional"`

	// Name: The name of the resource object.
	Name *string `json:"name,omitempty" parquet:"name,optional"`

	// Service Name: The Windows service acting as the object server for the resource object, such as Security or Security Account Manager.
	SvcName *string `json:"svc_name,omitempty" parquet:"svc_name,optional"`

	// Tags: The list of tags; <code>{key:value}</code> pairs associated to the resource.
	Tags []KeyValueobject `json:"tags,omitempty" parquet:"tags,list,optional"`

	// Type: The type of the Windows resource object.
	Type *string `json:"type,omitempty" parquet:"type,optional"`

	// Type ID: The normalized type identifier of the Windows resource object accessed.
	TypeId int32 `json:"type_id" parquet:"type_id"`

	// Unique ID: The Windows provided handle identifier for the resource object
	Uid *string `json:"uid,omitempty" parquet:"uid,optional"`

	// Alternate ID: The alternative unique identifier of the resource.
	UidAlt *string `json:"uid_alt,omitempty" parquet:"uid_alt,optional"`
}

func (v *WindowsResource) Observable() (*int, string) {
	return nil, ""
}

var WindowsResourceFields = []arrow.Field{
	{Name: "created_time", Type: arrow.FixedWidthTypes.Timestamp_ms, Nullable: true},
	{Name: "data", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "data_classifications", Type: arrow.ListOf(DataClassificationStruct), Nullable: true},
	{Name: "details", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "labels", Type: arrow.ListOf(arrow.BinaryTypes.String), Nullable: true},
	{Name: "modified_time", Type: arrow.FixedWidthTypes.Timestamp_ms, Nullable: true},
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "svc_name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "tags", Type: arrow.ListOf(KeyValueobjectStruct), Nullable: true},
	{Name: "type", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "type_id", Type: arrow.PrimitiveTypes.Int32, Nullable: false},
	{Name: "uid", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "uid_alt", Type: arrow.BinaryTypes.String, Nullable: true},
}

var WindowsResourceStruct = arrow.StructOf(WindowsResourceFields...)

var WindowsResourceSchema = arrow.NewSchema(WindowsResourceFields, nil)
var WindowsResourceClassname = "win_resource"
