// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_5_0

import (
	"fmt"

	"github.com/apache/arrow-go/v18/arrow"
	"github.com/telophasehq/go-ocsf/ocsf"
)

type EntityManagement struct {

	// Access List: The list of requested access rights.
	AccessList []string `json:"access_list,omitempty" parquet:"access_list,list,optional"`

	// Access Mask: The access mask in a platform-native format.
	AccessMask *int32 `json:"access_mask,omitempty" parquet:"access_mask,optional"`

	// Action: The normalized caption of <code>action_id</code>.
	Action *string `json:"action,omitempty" parquet:"action,optional"`

	// Action ID: The action taken by a control or other policy-based system leading to an outcome or disposition. An unknown action may still correspond to a known disposition. Refer to <code>disposition_id</code> for the outcome of the action.
	ActionId *int32 `json:"action_id,omitempty" parquet:"action_id,optional"`

	// Activity ID: The normalized identifier of the activity that triggered the event.
	ActivityId int32 `json:"activity_id" parquet:"activity_id"`

	// Activity: The event activity name, as defined by the activity_id.
	ActivityName *string `json:"activity_name,omitempty" parquet:"activity_name,optional"`

	// Actor: The actor object describes details about the user/role/process that was the source of the activity. Note that this is not the threat actor of a campaign but may be part of a campaign.
	Actor *Actor `json:"actor,omitempty" parquet:"actor,optional"`

	// API Details: Describes details about a typical API (Application Programming Interface) call.
	Api *API `json:"api,omitempty" parquet:"api,optional"`

	// MITRE ATT&CK® and ATLAS™ Details: An array of MITRE ATT&CK® objects describing identified tactics, techniques & sub-techniques. The objects are compatible with MITRE ATLAS™ tactics, techniques & sub-techniques.
	Attacks []MITREATTCKATLAS `json:"attacks,omitempty" parquet:"attacks,list,optional"`

	// Authorization Information: Provides details about an authorization, such as authorization outcome, and any associated policies related to the activity/event.
	Authorizations []AuthorizationResult `json:"authorizations,omitempty" parquet:"authorizations,list,optional"`

	// Category: The event category name, as defined by category_uid value: <code>Identity & Access Management</code>.
	CategoryName *string `json:"category_name,omitempty" parquet:"category_name,optional"`

	// Category ID: The category unique identifier of the event.
	CategoryUid int32 `json:"category_uid" parquet:"category_uid"`

	// Class: The event class name, as defined by class_uid value: <code>Entity Management</code>.
	ClassName *string `json:"class_name,omitempty" parquet:"class_name,optional"`

	// Class ID: The unique identifier of a class. A class describes the attributes available in an event.
	ClassUid int32 `json:"class_uid" parquet:"class_uid"`

	// Comment: The user provided comment about why the entity was changed.
	Comment *string `json:"comment,omitempty" parquet:"comment,optional"`

	// Confidence: The confidence, normalized to the caption of the confidence_id value. In the case of 'Other', it is defined by the event source.
	Confidence *string `json:"confidence,omitempty" parquet:"confidence,optional"`

	// Confidence ID: The normalized confidence refers to the accuracy of the rule that created the finding. A rule with a low confidence means that the finding scope is wide and may create finding reports that may not be malicious in nature.
	ConfidenceId *int32 `json:"confidence_id,omitempty" parquet:"confidence_id,optional"`

	// Confidence Score: The confidence score as reported by the event source.
	ConfidenceScore *int32 `json:"confidence_score,omitempty" parquet:"confidence_score,optional"`

	// Count: The number of times that events in the same logical group occurred during the event <strong>Start Time</strong> to <strong>End Time</strong> period.
	Count *int32 `json:"count,omitempty" parquet:"count,optional"`

	// Device: An addressable device, computer system or host.
	Device *Device `json:"device,omitempty" parquet:"device,optional"`

	// Disposition: The disposition name, normalized to the caption of the disposition_id value. In the case of 'Other', it is defined by the event source.
	Disposition *string `json:"disposition,omitempty" parquet:"disposition,optional"`

	// Disposition ID: Describes the outcome or action taken by a security control, such as access control checks, malware detections or various types of policy violations.
	DispositionId *int32 `json:"disposition_id,omitempty" parquet:"disposition_id,optional"`

	// Duration Milliseconds: The event duration or aggregate time, the amount of time the event covers from <code>start_time</code> to <code>end_time</code> in milliseconds.
	Duration *int64 `json:"duration,omitempty" parquet:"duration,optional"`

	// End Time: The end time of a time period, or the time of the most recent event included in the aggregate event.
	EndTime int64 `json:"end_time,omitempty" parquet:"end_time,timestamp_millis,timestamp(millisecond),optional"`

	// Enrichments: The additional information from an external data source, which is associated with the event or a finding. For example add location information for the IP address in the DNS answers:</p><code>[{"name": "answers.ip", "value": "92.24.47.250", "type": "location", "data": {"city": "Socotra", "continent": "Asia", "coordinates": [-25.4153, 17.0743], "country": "YE", "desc": "Yemen"}}]</code>
	Enrichments []Enrichment `json:"enrichments,omitempty" parquet:"enrichments,list,optional"`

	// Entity: The managed entity that is being acted upon.
	Entity ManagedEntity `json:"entity" parquet:"entity"`

	// Entity Result: The updated managed entity.
	EntityResult *ManagedEntity `json:"entity_result,omitempty" parquet:"entity_result,optional"`

	// Firewall Rule: The firewall rule that pertains to the control that triggered the event, if applicable.
	FirewallRule *FirewallRule `json:"firewall_rule,omitempty" parquet:"firewall_rule,optional"`

	// HTTP Request: Details about the underlying HTTP request.
	HttpRequest *HTTPRequest `json:"http_request,omitempty" parquet:"http_request,optional"`

	// HTTP Response: Details about the underlying HTTP response.
	HttpResponse *HTTPResponse `json:"http_response,omitempty" parquet:"http_response,optional"`

	// Alert: Indicates that the event is considered to be an alertable signal. Should be set to <code>true</code> if <code>disposition_id = Alert</code> among other dispositions, and/or <code>risk_level_id</code> or <code>severity_id</code> of the event is elevated. Not all control events will be alertable, for example if <code>disposition_id = Exonerated</code> or <code>disposition_id = Allowed</code>.
	IsAlert *bool `json:"is_alert,omitempty" parquet:"is_alert,optional"`

	// Malware: A list of Malware objects, describing details about the identified malware.
	Malware []Malware `json:"malware,omitempty" parquet:"malware,list,optional"`

	// Malware Scan Info: Describes details about the scan job that identified malware on the target system.
	MalwareScanInfo *MalwareScanInfo `json:"malware_scan_info,omitempty" parquet:"malware_scan_info,optional"`

	// Message: The description of the event/finding, as defined by the source.
	Message *string `json:"message,omitempty" parquet:"message,optional"`

	// Metadata: The metadata associated with the event or a finding.
	Metadata Metadata `json:"metadata" parquet:"metadata"`

	// Observables: The observables associated with the event or a finding.
	Observables []Observable `json:"observables,omitempty" parquet:"observables,list,optional"`

	// Policy: The policy that pertains to the control that triggered the event, if applicable. For example the name of an anti-malware policy or an access control policy.
	Policy *Policy `json:"policy,omitempty" parquet:"policy,optional"`

	// Raw Data: The raw event/finding data as received from the source.
	RawData *string `json:"raw_data,omitempty" parquet:"raw_data,optional"`

	// Raw Data Size: The size of the raw data which was transformed into an OCSF event, in bytes.
	RawDataSize *int64 `json:"raw_data_size,omitempty" parquet:"raw_data_size,optional"`

	// Risk Details: Describes the risk associated with the finding.
	RiskDetails *string `json:"risk_details,omitempty" parquet:"risk_details,optional"`

	// Risk Level: The risk level, normalized to the caption of the risk_level_id value.
	RiskLevel *string `json:"risk_level,omitempty" parquet:"risk_level,optional"`

	// Risk Level ID: The normalized risk level id.
	RiskLevelId *int32 `json:"risk_level_id,omitempty" parquet:"risk_level_id,optional"`

	// Risk Score: The risk score as reported by the event source.
	RiskScore *int32 `json:"risk_score,omitempty" parquet:"risk_score,optional"`

	// Severity: The event/finding severity, normalized to the caption of the <code>severity_id</code> value. In the case of 'Other', it is defined by the source.
	Severity *string `json:"severity,omitempty" parquet:"severity,optional"`

	// Severity ID: <p>The normalized identifier of the event/finding severity.</p>The normalized severity is a measurement the effort and expense required to manage and resolve an event or incident. Smaller numerical values represent lower impact events, and larger numerical values represent higher impact events.
	SeverityId int32 `json:"severity_id" parquet:"severity_id"`

	// Source Endpoint: Details about the source of the IAM activity.
	SrcEndpoint *NetworkEndpoint `json:"src_endpoint,omitempty" parquet:"src_endpoint,optional"`

	// Start Time: The start time of a time period, or the time of the least recent event included in the aggregate event.
	StartTime int64 `json:"start_time,omitempty" parquet:"start_time,timestamp_millis,timestamp(millisecond),optional"`

	// Status: The event status, normalized to the caption of the status_id value. In the case of 'Other', it is defined by the event source.
	Status *string `json:"status,omitempty" parquet:"status,optional"`

	// Status Code: The event status code, as reported by the event source.<br /><br />For example, in a Windows Failed Authentication event, this would be the value of 'Failure Code', e.g. 0x18.
	StatusCode *string `json:"status_code,omitempty" parquet:"status_code,optional"`

	// Status Detail: The status detail contains additional information about the event/finding outcome.
	StatusDetail *string `json:"status_detail,omitempty" parquet:"status_detail,optional"`

	// Status ID: The normalized identifier of the event status.
	StatusId *int32 `json:"status_id,omitempty" parquet:"status_id,optional"`

	// Event Time: The normalized event occurrence time or the finding creation time.
	Time int64 `json:"time" parquet:"time,timestamp_millis,timestamp(millisecond)"`

	// Timezone Offset: The number of minutes that the reported event <code>time</code> is ahead or behind UTC, in the range -1,080 to +1,080.
	TimezoneOffset *int32 `json:"timezone_offset,omitempty" parquet:"timezone_offset,optional"`

	// Type Name: The event/finding type name, as defined by the type_uid.
	TypeName *string `json:"type_name,omitempty" parquet:"type_name,optional"`

	// Type ID: The event/finding type ID. It identifies the event's semantics and structure. The value is calculated by the logging system as: <code>class_uid * 100 + activity_id</code>.
	TypeUid int64 `json:"type_uid" parquet:"type_uid"`

	// Unmapped Data: The attributes that are not mapped to the event schema. The names and values of those attributes are specific to the event source.
	Unmapped *string `json:"unmapped,omitempty" parquet:"unmapped,optional"`
}

func (v *EntityManagement) Observable() (*int, string) {
	return nil, ""
}

func (v *EntityManagement) ValidateObservables() error {
	presentObservables := ocsf.PresentObservablesOf(v)
	for presObsIdx := range presentObservables {
		var found bool
		for obsIdx := range v.Observables {
			presObsEnum := presentObservables[presObsIdx][0].(*int)
			if v.Observables[obsIdx].TypeId == int32(*presObsEnum) {
				found = true
				break
			}
		}
		if !found {
			obs := presentObservables[presObsIdx]
			return fmt.Errorf("non-null observable %s(%d) not found in observables array", obs[1], *obs[0].(*int))
		}
	}
	return nil
}

var EntityManagementFields = []arrow.Field{
	{Name: "access_list", Type: arrow.ListOf(arrow.BinaryTypes.String), Nullable: true},
	{Name: "access_mask", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "action", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "action_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "activity_id", Type: arrow.PrimitiveTypes.Int32, Nullable: false},
	{Name: "activity_name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "actor", Type: ActorStruct, Nullable: true},
	{Name: "api", Type: APIStruct, Nullable: true},
	{Name: "attacks", Type: arrow.ListOf(MITREATTCKATLASStruct), Nullable: true},
	{Name: "authorizations", Type: arrow.ListOf(AuthorizationResultStruct), Nullable: true},
	{Name: "category_name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "category_uid", Type: arrow.PrimitiveTypes.Int32, Nullable: false},
	{Name: "class_name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "class_uid", Type: arrow.PrimitiveTypes.Int32, Nullable: false},
	{Name: "comment", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "confidence", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "confidence_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "confidence_score", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "count", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "device", Type: DeviceStruct, Nullable: true},
	{Name: "disposition", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "disposition_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "duration", Type: arrow.PrimitiveTypes.Int64, Nullable: true},
	{Name: "end_time", Type: arrow.FixedWidthTypes.Timestamp_ms, Nullable: true},
	{Name: "enrichments", Type: arrow.ListOf(EnrichmentStruct), Nullable: true},
	{Name: "entity", Type: ManagedEntityStruct, Nullable: false},
	{Name: "entity_result", Type: ManagedEntityStruct, Nullable: true},
	{Name: "firewall_rule", Type: FirewallRuleStruct, Nullable: true},
	{Name: "http_request", Type: HTTPRequestStruct, Nullable: true},
	{Name: "http_response", Type: HTTPResponseStruct, Nullable: true},
	{Name: "is_alert", Type: arrow.FixedWidthTypes.Boolean, Nullable: true},
	{Name: "malware", Type: arrow.ListOf(MalwareStruct), Nullable: true},
	{Name: "malware_scan_info", Type: MalwareScanInfoStruct, Nullable: true},
	{Name: "message", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "metadata", Type: MetadataStruct, Nullable: false},
	{Name: "observables", Type: arrow.ListOf(ObservableStruct), Nullable: true},
	{Name: "policy", Type: PolicyStruct, Nullable: true},
	{Name: "raw_data", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "raw_data_size", Type: arrow.PrimitiveTypes.Int64, Nullable: true},
	{Name: "risk_details", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "risk_level", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "risk_level_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "risk_score", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "severity", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "severity_id", Type: arrow.PrimitiveTypes.Int32, Nullable: false},
	{Name: "src_endpoint", Type: NetworkEndpointStruct, Nullable: true},
	{Name: "start_time", Type: arrow.FixedWidthTypes.Timestamp_ms, Nullable: true},
	{Name: "status", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "status_code", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "status_detail", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "status_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "time", Type: arrow.FixedWidthTypes.Timestamp_ms, Nullable: false},
	{Name: "timezone_offset", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "type_name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "type_uid", Type: arrow.PrimitiveTypes.Int64, Nullable: false},
	{Name: "unmapped", Type: arrow.BinaryTypes.String, Nullable: true},
}

var EntityManagementStruct = arrow.StructOf(EntityManagementFields...)

var EntityManagementSchema = arrow.NewSchema(EntityManagementFields, nil)
var EntityManagementClassname = "entity_management"
